apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-production
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/production
  prune: true
  wait: true
  timeout: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
