apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ../../../base/productivity/open-webui
  - ./ingress-route.yaml
namePrefix: public-
commonLabels:
  app: public-open-webui-deployment
images:
  - name: ghcr.io/open-webui/open-webui
    newTag: main@sha256:c792953395b43d4f49085fa4026850c5e923578345ebeaf56eabd980bcfc273a
patches:
  - path: ./patch_deployment.yaml
  - path: ./patch_service.yaml
