apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ../../../base/productivity/open-webui
  - ./ingress-route.yaml
namePrefix: public-
commonLabels:
  app: public-open-webui-deployment
images:
  - name: ghcr.io/open-webui/open-webui
    newTag: main@sha256:8b432fe0a65b91116afc7961365c6cca5379cc923171386a96691f3471f3cae9
patches:
  - path: ./patch_deployment.yaml
  - path: ./patch_service.yaml
