apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ../../../base/productivity/open-webui
  - ./ingress-route.yaml
namePrefix: public-
commonLabels:
  app: public-open-webui-deployment
images:
  - name: ghcr.io/open-webui/open-webui
    newTag: main@sha256:a26effeb220e132482bf7e0560b3404843e7bc40d23051144e062960df8df6b0
patches:
  - path: ./patch_deployment.yaml
  - path: ./patch_service.yaml
