apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
spec:
  template:
    spec:
      containers:
        - name: open-webui
          volumeMounts:
            - mountPath: /app/backend/data
              name: config-data
              subPath: open-webui-public/config
          env:
            - name: OLLAMA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: open-webui-public-secrets
                  key: ollama_api_base_url_local
            - name: ENABLE_ADMIN_CHAT_ACCESS
              value: "false"
