apiVersion: v1
kind: Secret
metadata:
  name: open-webui-public-secrets
  namespace: productivity
stringData:
  ollama_api_base_url: ENC[AES256_GCM,data:Z143HcrkGOkDGeOOXgCHyiExXcZMAebup+7VgY3XgQ==,iv:pmw2tZ7IcwfAX3OdjfAySughshuAI4ZLVbN+7veARw4=,tag:cAiEJErbUn7XOqAIRFmATw==,type:str]
  ollama_api_base_url_local: ENC[AES256_GCM,data:a8185BGxuzhTeQT5PjANyQW3lB1aWe3A5ze3VCHs+BXbADMH1g==,iv:O8eaC7s9dowQe0UttTcqOVBHBpQVeRHX+WZdsNKlgUo=,tag:P6YMdgQnGED9IBPZPUuBIg==,type:str]
  oauth_client_secret: ENC[AES256_GCM,data:7xI5vz0m1yMfMFpYeysjfutkD+qoyuY7atOw6S3Qcz94HSeXTmlFSMyUuTlP2y8UcsPn5QD53WNzyq62YxrC0Q==,iv:mQJvQEkO7RZ0EhE9YeqTp4mQSlVjDJrN3q5CrGiQHJ4=,tag:zqUCLd73cmaKtE1xOBdKlA==,type:str]
  webui_secret_key: ENC[AES256_GCM,data:Vu8GGkqQXDMwpBjFgx7DsdTvmnPpZJ5UZ+COhZnG5hBlYAB1gXFymLBrRC1ytiNQ0/YWwkbga461k2F35Ic9rQ==,iv:3qcZY2WSq9ftnYXjPiFVX6jrhSHkFU3SFcslTi1VbXs=,tag:f4C0KUAA3kOKVm4zf0Rq7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL2ZLaVNQZFFQT09XVlhP
        am56RVJ2bzBNblJ1eU5GanZ3UGo4VnBGd2dBClJEZkJZcnI0UWxoRFg3b0lheU9t
        L1QwWjZsTEhUWklqcWhYRktYKzByNTgKLS0tIE9GOUpOb20xM1Jad2xYUC92ZmQ5
        YkdmTnRZOVdJYnU1OHVETUZ5dHZGQlkKBqiA4H97rSqRUtDzHfSKK+Txquk0wQRL
        nPk1x5DHsnNmhm8f1xG7KVjSfvBQbAwhqBMygB2MyH8uAmkli4WqDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTWVyeGpDdWM5L0Y0YXlB
        SUVUOWhtTW8yQXpkSWhEOCtibTQwblJXRmxBCnJ5TTZQM0U2WUxUZGpnaEtzY0Vz
        Sy9UdnZtdElHbUZWSFNnUnViS2hlRWMKLS0tIHRKVnVEY1ZGVmxJS2daT2FRVTkr
        NUR4cWI5Vm1McmE3U21naEF6MlBxOFkKLXat0DRbwZQkHj6NVS7o3Uqk2LkUN6wK
        Q8uTx0rqOrPyFN2cdS+MyWB9rKfo1y9ty+SXhQ9ccsA9owWw3rAC+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdkxIb1VOeEgxRWlBS21U
        TXZSaGtaSjRJclBDcklKRCtwenVzbW10ZlJZCk85WWw5TTBJQXh2RXR1bzZJbWtM
        cExzZmV2QVpoY3E0Z1VvNDRvV3F5M0EKLS0tIEMxMFA1TWJKZGsrUTBDa3kzUVRZ
        ZkY1YUQyNVVJcW1SSWpBNEhqZElKWVUKhzXFxjlVF72GI13IEBdt3O54ZlXpyEp/
        Xh0np90qE/Q1ejjUSUBO1/wsBCjAMYOq+gUnPnGYV0TRQ50JZY14bg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T00:59:33Z"
  mac: ENC[AES256_GCM,data:fQg2LsWLjgZ0YcVoOp4fomnzR7kRrBbMGtHY5m7C4mmCO3QGi5fVSg9cMxCfYoEoMrVrRMHOg4WTKHMBkYqJevOI5f3ogPZ0gIk+/Vaq2ed1Vrt2UMYQPX20wX0kp3Q9QpnUWZDV1xRTtLO/WI4VHN7eW4/4nzO1yxTGn5NfOLs=,iv:ZHw9fYLZnCZOlWRn+O736uIoIIbwi5zsekqVKQTp9f0=,tag:5lQWyEyTz6lbOMhYXmY3hQ==,type:str]
  version: 3.13.1
