apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName authelia-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *deploymentName
  template:
    metadata:
      labels:
        app: *deploymentName
    spec:
      enableServiceLinks: false
      containers:
        - name: authelia
          image: docker.io/authelia/authelia:4.39.20@sha256:1b363e9279e742397966333f364e0876ae02bf5c876de73e83af6d48c57ff51b
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/London
            - name: X_AUTHELIA_CONFIG
              value: /etc/authelia/configuration.yml
            - name: X_AUTHELIA_CONFIG_FILTERS
              value: template
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
              value: /secrets/storage_encryption_key
            - name: AUTHELIA_JWT_SECRET_FILE
              value: /secrets/jwt_secret
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /secrets/session_secret
            - name: AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
              value: /secrets/smtp_password
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config-volume
              subPath: authelia/config
            - mountPath: /etc/authelia
              name: configmap-volume
              readOnly: true
            - mountPath: /secrets
              name: secrets-volume
              readOnly: true
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 200Mi
      volumes:
        - name: config-volume
          nfs:
            server: ${NFS_STORAGE_HOST_FAST}
            path: ${NFS_STORAGE_CONFIG_DATA_PATH}
        - name: configmap-volume
          configMap:
            name: authelia-config
        - name: secrets-volume
          secret:
            secretName: authelia-secrets
