apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugin
  namespace: flux-system
spec:
  targetNamespace: kube-system
  path: ./apps/production/kube-system/intel-device-plugin
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  retryInterval: 1m
  timeout: 5m
