apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin-media-service
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: media-service
  path: "../../../base/media-service/jellyfin"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: jellyfin-deployment
      path: patch.yaml
