apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Flux Kustomizations
  - ./nginx-test/ks.yaml
  - ./jellyfin/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./prowlarr/ks.yaml
