apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:x5T4SD1BH1WXmKnEmHfuOtrcBTDEmxrjkPlnWG2Y8bnHhqG+x6xbtmW0Ww4yMex/U68NB7dXFPjpnYHRaAReThezQR4=,iv:gLu6yWQiHE2cQIWUr2/u91WpWq2gvbclN96R8tGq8OM=,tag:OK7OVtv4JRFK6aLwRgCxfg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaalNwaXBET3VmTjNtcFIv
        T3ZKcnBMbTh6eXR1b28vVSt3VzRWT24vZ1VjCk1FWlU5cDY5TXZyMGVidUVaVTdO
        cHE4SUMzK3pZWW1wbFVUSW9WakpjVGcKLS0tIDNEcnh2SGw3djVGLzkwUTNuSzI3
        SnY5cW1LSlZSTCthZGxXQ0hFdUpidU0KYEsL/GkJtwnmcuT+hNuu25rHYN0rOS/H
        FwDmjffDukwIhjzKpYTi+vH63Xqnfv5d2yYFxLTi5YnnEFbEcedSdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNXFoTU1aMkZFTlBvQjI2
        aDlZeDNHK0h2NjdNck1aaHRPMmtzZ3lvR25nCkgwakVudW5DVGFBQXdETVEwazNK
        dzB4WHNmNndZUTJYMWlqSWlGL3A0QlEKLS0tIGdyZ3lQS2FtRGVFM2xYL05IZGlT
        YUowQ2cyQ3BKVXIxcVZNOHE5TFZzUVEKjEfoKVrYXVWQ4NBB6SOAoOZkpuzJ+0F8
        lXssLtGPILMuxmYqHamzngBknXt6F9N7lDnWL85iaRLEHerbvpciQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdzZIT25TWEdkYWlEREt1
        QUE1SjVON0hXaXlkRnpIbkJvaHdWdWNPTXpnCmcxMzZjaXVteDhxc2pKcWVJeWNR
        dTNHTDY3dFpTckFoTG5OVHFqTXdudlEKLS0tIEFpQUdkQlFrSjZvZDRQSjNmS3Ri
        aFgvRHVVMWNJN0xBWkxqcjhDd2V2aFEKQYQSPECXyJPt1X2QyWxSTkQlq1HTtBhU
        WqfBhAWSK5z4ji13mY1LofemKBKZiW9bUFNl4SRSRzAPT9UIvsThLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T23:41:42Z"
  mac: ENC[AES256_GCM,data:0mWygUzCeQ0Neq30Vlr9RJLrAd9QUFvKmXX9dDxlTe+S8DvWRrchr4tmMeiTRqn1F2rjj3tWnxaHVRgZ9Cmms856pDEDyhNabUBJ4VSFyTJ3YA47uUPZcykvF9b97BUbjhfMe96xrqWJMdGSD5Qt0eBFYl3iDN39V0xqxEY+Nro=,iv:4mM8xYg0qVQIki80HpKGZpNHjkLGMLOv2JeVVMFF9HQ=,tag:SW9c3O9kQswXR9UtSxSVFg==,type:str]
  version: 3.13.1
