apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:mimndiW14TeCqQOBdXbOO3ksf/obpy5gCvl9vYB2lee7i/49hLnpMNfRTZjs3yt37C6Xb2LM8yOo339em/CW4nEAhBbVay2dViTXbqN6AS6fIiNwkk1X9hWySdNUxoXUSunzVnyppMXTXxwTstg2shgmWIB9eIXEeF1H0vVLCA+ywfOx5P/XHYzIJrWwQhmeIaTOB/20saizqCoBii1uCLD8AscJQvQl7GUHTdK/tnxp+/O9T4KVPYfPxXRToVmwC00aGoiZt3xfierL1r63fhXDEHHP+l/KKqOGYswctpqRlqT3+fco1VRdluK6esin,iv:yLDw41zWrr+Q6M2wUE+cluoCL/Ra4n0KAZxbKWaw/nA=,tag:U741CCKefzuMNkgOMNN1Ow==,type:str]
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: productivity
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Rnl2VVdBdXlsYWM3dmlW
        UUR4cUxadUNGaTZSVk9KNDZqWTJRa01mWFZRCjFvTkpoSlRaM3cxNExDZGlYSkxs
        YVd4MGptWHdHTFQ0dVJ1VUV1RzY0S00KLS0tIG9ZRkhOb2tXQjcxdmFLa2tmbHQ1
        WmlFSEM0b0xwVXREWXc1Tm9DV2JhWjAKonZh84AB7VJZOENZ3cSkS5fZtGbJBkGV
        eh8kak/djlyp0XnTCLRo80mCldC1XQTrjbHS3jK5IspS9sWrAOkoBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUnk3MU85MS9uVnVaY1pD
        emIrMlRKUGxndjhRT3VBd21kQUx2ZlZwK3lvCjVGM2V2amlwMHNCNXo2Vjd4Z2l6
        RUxlTTFKMCs3bDdacjJ3SWhsRmZTWEUKLS0tIDlualNGS08xRXIyd21aRjNERDFu
        SytOY3g2c0U0ZEZ2MXR6RFJGSlNzUWcKdbBI42+dmFbyMLjrRYjehhUvmpPvqw6S
        96QnUn78cr4P9eQt03a4aAzW8bYDva3kzfWkeU0eqXR6AQvE43DRGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUzFHUWVwM0c1Y2pXbmty
        QjU3T09HbmdoVzlRY0lZUU41akZkWHU4bG5VCnk0Mkx4V0JOL0dtbS9ZSGFWNWp2
        cHAwSENwejVFbzNZNG9YbUxSdnl5NXcKLS0tIHJvT0pJZy9sZ3dZR3NtbjlnZU5l
        WTh6R3l1b3VnM1FkMWJqamN1U1N4OEkK+oFGL//XZkjRsBh5aimABrsjaoD132tk
        0ia2CJ9nSISGKa+BXrftK5ucZxJmhdCqrVcthK2lf7ZGWoUh6N4sow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-23T23:00:42Z"
  mac: ENC[AES256_GCM,data:bMgzUCtFATZLhlJ+Gfcit8mSYtbZfTwr08/m1PoSz89jpogA7YNIaqEn30+MkE8ijh4Nh0xaBezZwDgPhckjS1AhmYmVvcXGrny5xtnERz0SX6/D/GGIOZbEdRTlNajq1VsgbyEgjE9PXcsCeN0SOwVDCRfDaulVooukXKaedAg=,iv:AffDraPCn9NdjcfNj8qMowBZcuihxuYqfW7SbXwV2iM=,tag:WKDkpjR7PzC+xqkBZWStKw==,type:str]
  version: 3.13.1
