apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:rWFvtYkX1CfdesDNhe5XwGfch2Dkur42P+mJpxyIQOB9jAndUJ9KgwKHOxYrfTOJgHqdpSAyD6U9fe8fv7YhOMeV8NC2LK4vnhDp7d5BO3fy+0o2Gy3nsnl9aXiCZa94ZCAFYRgZc9riguJpYpcnHeHxISgltA7+hiOijSP4EFfvWniDOe1SgWHUQ5nfKb4LKDG5ImSOlOW6YPvpgdfJ8L0052a3G9SVO7driSGZPK9Im6niHlXqjdgw/9hsk4rmzPi9a3Hld+JL1G1l7gP9V8VwjY8eZy80RVT/ewFMBltfFJJnN7zfE6MR6cfXBTnv,iv:AVM/DXDIPvk6NauignPhHxBegCkZKpg8VUpPT21jgKI=,tag:dgmn8q2gYmlTO2+VMTBMGA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaalNwaXBET3VmTjNtcFIv
        T3ZKcnBMbTh6eXR1b28vVSt3VzRWT24vZ1VjCk1FWlU5cDY5TXZyMGVidUVaVTdO
        cHE4SUMzK3pZWW1wbFVUSW9WakpjVGcKLS0tIDNEcnh2SGw3djVGLzkwUTNuSzI3
        SnY5cW1LSlZSTCthZGxXQ0hFdUpidU0KYEsL/GkJtwnmcuT+hNuu25rHYN0rOS/H
        FwDmjffDukwIhjzKpYTi+vH63Xqnfv5d2yYFxLTi5YnnEFbEcedSdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNXFoTU1aMkZFTlBvQjI2
        aDlZeDNHK0h2NjdNck1aaHRPMmtzZ3lvR25nCkgwakVudW5DVGFBQXdETVEwazNK
        dzB4WHNmNndZUTJYMWlqSWlGL3A0QlEKLS0tIGdyZ3lQS2FtRGVFM2xYL05IZGlT
        YUowQ2cyQ3BKVXIxcVZNOHE5TFZzUVEKjEfoKVrYXVWQ4NBB6SOAoOZkpuzJ+0F8
        lXssLtGPILMuxmYqHamzngBknXt6F9N7lDnWL85iaRLEHerbvpciQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdzZIT25TWEdkYWlEREt1
        QUE1SjVON0hXaXlkRnpIbkJvaHdWdWNPTXpnCmcxMzZjaXVteDhxc2pKcWVJeWNR
        dTNHTDY3dFpTckFoTG5OVHFqTXdudlEKLS0tIEFpQUdkQlFrSjZvZDRQSjNmS3Ri
        aFgvRHVVMWNJN0xBWkxqcjhDd2V2aFEKQYQSPECXyJPt1X2QyWxSTkQlq1HTtBhU
        WqfBhAWSK5z4ji13mY1LofemKBKZiW9bUFNl4SRSRzAPT9UIvsThLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-23T22:16:21Z"
  mac: ENC[AES256_GCM,data:s8bEPAWYVMsvgxlBk+jJLs3SwnTCpevJ9dJ9F+TFJfxhUkquSXUXoPNiPMcEUMYQbarZiBXqtAXhSRh1f18sPc1VGFhlgveatPUSKsEQTSXktmTuejA3iVG9R5eR4uZ+0jiAn2secILXh13SePwRggQCMV0YOOoIno1uO22vh8I=,iv:hPDVkzN7IYGd8YVoo1Nh8KttvsXFm+dWE5Sa/gTQ5z4=,tag:Vp9hMoChsUrrHOCip/nilQ==,type:str]
  version: 3.13.1
