apiVersion: v1
kind: Secret
metadata:
  name: wayom-secrets
stringData:
  jwt_secret: ENC[AES256_GCM,data:eYxSQUClwuUdrGyJZOSYhy8r8sHwi2XFzVEGV8Zq4Q==,iv:3JZc7syXClBpLbQwe9FsEUOnp6Y1aZdKKyja27/lqe0=,tag:WRUzsUN8clem7VVRnWWOxg==,type:str]
  github_oauth_client_id: ENC[AES256_GCM,data:JZD4jGAp64y6gTEZH74wX88U6gA=,iv:oqradzKdGHimmC4F8oVTVK8iz2tAqns6LaYQG024WW0=,tag:7iD99KHh5TfB5dTkopAJfQ==,type:str]
  github_oauth_client_secret: ENC[AES256_GCM,data:6sYl+POnwcUYgdSc20yP2Pw0h4j62gecDc1d/Lba+sbII6UMhMGy0g==,iv:7hOQNIfDROo+Hk+/+UaouumW5OCv+WpG44cc9s33owA=,tag:bm+chXAVJzU6inO7j4TfBQ==,type:str]
  github_oauth_redirect_url: ENC[AES256_GCM,data:DiCHEM0HXHKy1sNzyvy6Hhddigh0U/yoAs8JnNMnuvD7nJFRDg/+buAVG14d2jczjEyqFhQ+Uw==,iv:6ZSH1Sv+nGgDTsCtWAqshZ/oTMlV1EkrZePtw0sMuts=,tag:MZa9TJGBF0HsM2sRTpc3Og==,type:str]
  lunch_flow_api_key: ENC[AES256_GCM,data:V42HojFQ+SkCXxWOCnhTBIW9YyUQt7AxHW9VGLpLZswNCID7lvBC8kAwhOT0vKgA+143cfVwVLgfDrU6wFabzQ==,iv:o0BhfTvoL8colbWT9n+3dUodyP00mvUi+nzUuXO1UGg=,tag:SH3u3OiyjSxzt8zpbIA7Vg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzczdRcmczVFc5WlB0UWRP
        RjVWaWZOekxMcU1BaHJKQ3BYT0t2Qkoyb3lZCnFaanVTQjFiWElNY2h5N3JnUWRF
        N2VjSmoyU05EWUFUd1l5REFwdVdTVHMKLS0tIHNtMlFaM2ZJbWZhMEZ5bDkvZWs0
        Sy9DYmMrdlN3Zno5T2dBU2JZRUVXWmcKGMDcedMHvJD3tBKBBUQ9xlgxrvnviQ7x
        4S/ecZGtb+5npB6OQ+q06/tfLcggaxZv4ipNDGLwf3TiGbikXLUNTQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NXRPTUtYQmIxMnZDMTJq
        U3N1NzdxTUhaRWE3SzA4cjI1dC9ucVd3UUZrCnV2VGtQZmJYcGcybnZiV3ZWQytL
        dlc3aUQ5YmRFZ0FtNk1HMTFQWGN3UDgKLS0tIHJRNkZWM2pib3c2WFUydTQ4SDVv
        aCtmb2ExMWRSNDBzMVl4Ly9VaUwvUEkKzmXWslpA5cEdXT47Yp5jHEssmPXAytSr
        7lYZo7B86KsAYhlLE4vCgt1oYzeWqu9KGdljqoMmIleiNwWDYvHvbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdkNZbXhhT05DTjVyY2NI
        OWpiTk9lckFYRXQzZHlkZmJaR0hiRUc5am00CkFUd0ZTLzFVMzkydHdxeTI1NFNW
        RS9GdXZZSVM5ZzZpTGcrTDBJMmpHd2cKLS0tIHlLcjJreEMvSURXaHdISWJtYmsy
        ZW4xWDRLdmNRV0dvaFFMd2RrTFBabmsKRDqdWMcdyBh2ZDK50gjPPJ2xwLn3mBLo
        g46o5PmfvY2JpszuqxmXjuYEWKdXfLfNIs0JqxzQ7bZgD30gUGI1rQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T07:39:38Z"
  mac: ENC[AES256_GCM,data:g8Pb/S3liVXeL6ToJB+Oi8/B2fmD0a6GBtIauiNdsDGvek2gcC13vbzb3MwfTxnO8lf9GDcFIQnmrRCXuzBZK0tXGC1nil+xDN+Yvk/gbfbF1ONkyptaQR+Rzra+oq7G63wTqrY14qJ9v7zFr+VHxYo1tel8X4foJZp9Y18vC04=,iv:ahT50Oc6eSboiuJIW9FWG10IfTcVO7KjrePPMENy+uU=,tag:1F+rdDL0xOmQj4XUcZewxA==,type:str]
  version: 3.13.1
