apiVersion: v1
kind: Secret
metadata:
  name: wayom-secrets
stringData:
  jwt_secret: ENC[AES256_GCM,data:VWB81A3HYwCPM/HN8bX4zn4Xmqc4uHH08V6Jhn9B5Vc=,iv:7cdkDWKR/qM8OzHPaJ9PbMEQuhPk2sGQ+e92teHmdms=,tag:lUnLpK5OsGSXwEEIfD4AMg==,type:str]
  github_oauth_client_id: ENC[AES256_GCM,data:1DTQFFJvJ9C0SZCW6Dt6+o5Kn74=,iv:buAFSASMNtnN297TkFYM1pCNdLxrjihbcw1vjSXlmAE=,tag:uu2EC7gTy1b5PlSJ46O6bg==,type:str]
  github_oauth_client_secret: ENC[AES256_GCM,data:7iybwKaEtxol9CoCNrtBM53r89l+Dd/cIfuowDBcdtJq/CankRjnQA==,iv:z36xbZZRilk72ESyJg1UN098zdY4BqzdgS5GlRz+u7M=,tag:uffuyrw3KYZePjmQ7tlN8A==,type:str]
  github_oauth_redirect_url: ENC[AES256_GCM,data:JqMS/bsmq0AMKid/FoydajZl8+0kPKLbUQJ3iirACV/e7An2jroSFMbK6exZrPBo3HDmDAbfaw==,iv:g5F8T+IPUB+pwnt2Tji9NrrCF3aBUml1KaVxn/EIzt0=,tag:YdSfZkrYVn4hpSE0v5nXsg==,type:str]
  lunch_flow_api_key: ENC[AES256_GCM,data:6tD95+R5xUvzev4Dsd+YtpkZahKk+K7usuqIq/PXfMWqe0rcjbCcqMUe3zbb1oQokc0loeljwsgR9NCcEOeEDg==,iv:Qanpe12fKu7L/KaKIEcN8pS0KnekljsgSk5rOuLjK/U=,tag:9VwZTTNR7em8RCTErCd0bQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVnFYUHM3MW56Ymp3YXZZ
        ZTJ1ZFNhckdEZm1ZR1k2alV4VGE4VnhOSUY4CjJleFFkZUswTUJXVHZ4WlBuUlhj
        RTlrNmxpSDRHUWd0UjRGbkl4UC8zZWcKLS0tIEM3dG9lZ00wejZZNk9FV1pYdVRY
        QzJmbThxTjVBUGRmcm1SWkRBMGttSG8KvW0oxRciYdG4KRQwce+RI1ZFbJZS3lfy
        zxKpATw+3urshlP/YHqTnuSEq6W2u2SOgXdXnVq9tzv5bjHqlHLZMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYUJoRG1CaFhwYjNjRjB3
        dHJlNzdQRGE0MDFvOHVQY3hZaEttK3QybWwwCkw2ZzJYR0IvcW1TL1g2MWVaUnBQ
        NllhMXhDOVA4TFI0UGV4VFhMT2hhRWsKLS0tIERWY2ZwOG94dGVSNzV3Y283YnJ1
        dm41dm9uSzJPTG1ta3hZRzA4UTJ1dUEKJLolJlmEBLWJAgxZBE6lX97tyYpYjPUU
        AkzAAkK+BUOlQrqyN732rXm+Pc2cfQe2zobBjDjUPliPchyTfY8d8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSE82SnJ2cWY3Wk1EREFl
        UE16UVRaOUNUS3JqSnpCcmpYUGc2aDg1bDFVClNrUWRNTEoyZGpPa21sbGdKd2Z1
        WHJwQVl1M0h5Vk1xT3ZBaFIvMnhLR2MKLS0tIDVHVGRCMVhaY2FEUHlKc3JoOC92
        WFR0U1JYNUVsdXRuZ0xZMW52NENIbXMK7FU+MSzmMjQzEd9aHepJINjLCvvZaqAh
        pqKQeHuAHR/lBtf8J8jfd3pwslSxuKlpNilI9Oj132UTA65F6hcGHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-21T10:50:07Z"
  mac: ENC[AES256_GCM,data:bR2NqHU1pqfhSIWEfTVEuf764kUdUCPArNeK5CaaXkQ0GdC4KQmLq29odK2LMjJEv2+lc0RAHGGZaHBTf8YfcCEQqQPMtcC2HgCM3XnXHWXEfaOak57rgSni/0ybTEN3NuykSH56QyfqhaF8hVxQ6UclJHnX4c9CczbghZakdoY=,iv:eTit5n/uwtBYQ/S6EfqvG5cWdl7xGlyAruoB9Ztwfmk=,tag:8xc6T45YY/8KfwI1uQQ2Fg==,type:str]
  version: 3.13.1
