# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.9.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs-charts
      interval: 5m
