keys:
  - &mbp16 age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
  - &mbp14 age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
  - &cluster age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
creation_rules:
  - path_regex: '.*\.(sops|enc)\.ya?ml$'
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - *mbp16
          - *mbp14
          - *cluster
stores:
  yaml:
    indent: 2
