apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: readarr-media-service
  namespace: flux-system
spec:
  targetNamespace: media-service
  path: ./apps/production/media-service/readarr
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  retryInterval: 1m
  timeout: 5m
