apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-service
spec:
  selector:
    app: flaresolverr-deployment
  ports:
  - name: http
    port: 8191
    targetPort: 8191
    protocol: TCP
    nodePort: 30191
  type: NodePort
