apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName bazarr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *deploymentName
  template:
    metadata:
      labels:
        app: *deploymentName
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1001"
        - name: PGID
          value: "100"
        image: ghcr.io/linuxserver/bazarr:latest
        imagePullPolicy: Always
        name: bazarr
        ports:
        - containerPort: 6767
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config-volume
          subPath: bazarr/config
        - mountPath: /movies
          name: data-volume
          subPath: jellyfin/media/movies
        - mountPath: /tv
          name: data-volume
          subPath: jellyfin/media/tv
        - mountPath: /anime
          name: data-volume
          subPath: jellyfin/media/anime
      hostname: bazarr
      volumes:
      - name: config-volume
        nfs:
          path: /mnt/mospeed/swarm-config
          server: 10.0.7.202
      - name: data-volume
        nfs:
          path: /mnt/mopower/swarm-data
          server: 10.0.7.202
