apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-media
  namespace: flux-system
spec:
  targetNamespace: media
  path: ./apps/production/media/immich
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: cluster-configs
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
