apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./secret.enc.yaml
  - ../../../base/media/immich
patches:
  - path: ./patch_helm-release.yaml
    target:
      kind: HelmRelease
      name: immich-deployment
