apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-deployment
  namespace: media
spec:
  # See https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml
  # for the full list of values that can be overriden
  values:
    image:
      tag: "v2.5.6"
    immich:
      persistence:
        library:
          existingClaim: immich-data-pvc
    server:
      service:
        main:
          type: NodePort
          ports:
            http:
              port: 2283
              targetPort: 2283
              nodePort: 32283
      persistence:
        external-data-main:
          enabled: true
          mountPath: /usr/src/app/external-data/main
          existingClaim: immich-external-data-main-pvc
          readOnly: true
        external-data-ftp:
          enabled: true
          mountPath: /usr/src/app/external-data/ftp
          existingClaim: immich-external-data-ftp-pvc
          readOnly: true
      # nodeSelector:
      # kubernetes.io/hostname: knode3
      # intel.feature.node.kubernetes.io/gpu: "true"
      controllers:
        main:
          containers:
            main:
              env:
                DB_URL:
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-app
                      key: uri
    valkey:
      enabled: true
    machine-learning:
      persistence:
        cache:
          type: persistentVolumeClaim
          storageClass: nfs-csi-default
      # nodeSelector:
      #   kubernetes.io/hostname: knode2
      #   intel.feature.node.kubernetes.io/gpu: "true"
