apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-deployment
  namespace: media
spec:
  # See https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml
  # for the full list of values that can be overriden
  values:
    immich:
      existingConfiguration: immich-secrets
      configurationKind: Secret
      persistence:
        library:
          existingClaim: immich-data-pvc
    server:
      service:
        main:
          type: ClusterIP
          ports:
            http:
              port: 2283
              targetPort: 2283
      persistence:
        external-data-main:
          enabled: true
          existingClaim: immich-external-data-main-pvc
          globalMounts:
            - path: /usr/src/app/external-data/main
              readOnly: true
        external-data-ftp:
          enabled: true
          existingClaim: immich-external-data-ftp-pvc
          globalMounts:
            - path: /usr/src/app/external-data/ftp
              readOnly: true
      # nodeSelector:
      # kubernetes.io/hostname: knode3
      # intel.feature.node.kubernetes.io/gpu: "true"
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                tag: "v3.2.0@sha256:ae13784ffcfcce8f4178113eb6661602a1fd1912f3d539880b8ac0dd95fc8ac2"
              env:
                DB_URL:
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-app
                      key: uri
    valkey:
      enabled: true
    machine-learning:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: "v3.2.0@sha256:f8b2869891c861a58dde969d86e7ea8a186e6059a55886632ee3249e51fb574a"
      # nodeSelector:
      #   kubernetes.io/hostname: knode2
      #   intel.feature.node.kubernetes.io/gpu: "true"
