apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-deployment
  namespace: media
spec:
  # See https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml
  # for the full list of values that can be overriden
  values:
    # image:
    #   tag: "v1.120.2"
    immich:
      persistence:
        library:
          existingClaim: immich-data-pvc
    postgresql:
      enabled: true
    redis:
      enabled: true
    machine-learning:
      persistence:
        cache:
          type: pvc
          storageClass: nfs-default
