apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-deployment
  namespace: media
spec:
  # See https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml
  # for the full list of values that can be overriden
  values:
    image:
      tag: "v1.120.2"
    immich:
      persistence:
        library:
          existingClaim: immich-data-pvc
        external-data-main:
          enabled: true
          mountPath: /usr/src/app/external-data/main
          existingClaim: immich-external-data-main-pvc
        external-data-ftp:
          enabled: true
          mountPath: /usr/src/app/external-data/ftp
          existingClaim: immich-external-data-ftp-pvc
      defaultPodOptions:
        nodeSelector:
          kubernetes.io/hostname: knode3
          intel.feature.node.kubernetes.io/gpu: "true"
    postgresql:
      enabled: true
      primary:
        resourcesPreset: large
    redis:
      enabled: true
    machine-learning:
      persistence:
        cache:
          type: pvc
          storageClass: nfs-csi-default
