---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-pvc
  annotations:
    # Prevent Flux from deleting this resource
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-default
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-external-data-main-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: immich-external-data-main-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-external-data-ftp-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: immich-external-data-ftp-pv
  resources:
    requests:
      storage: 10Gi
