---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-default
  resources:
    requests:
      storage: 100Gi
