apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
stringData:
  immich_secret: ENC[AES256_GCM,data:iPePWR/3OS3kGE0=,iv:ZKBqFY9XvexN4Nec2D02vmJZX6+kdWW/+0sMBkf2CFA=,tag:ajK2CHktzY5OLf2OpiAe8w==,type:str]
  immich-config.yaml: ENC[AES256_GCM,data:JM3/PAjLYLxwYZ2b3wuJKZSnOb46EEAQDzR1uplclxkBomg/avJUQ43fJMapVyuwRwUOxYgTRvvcFVmpyqsFKavUNPqgELywYDkw2iwvb5c+Llr7DeAUwG6w3iD2GpwgW84XAM9+ZyehIYtXiabQyX6KKH/58q2pnrjGrkpJDDdOLKAwBGUiarSHkzEIh/pMdtjtESInqgET42DQdVMmPyQe7bJQM2+2GBd9r6CpS8O71J0+iCXvi9YWLdVtkWyTbDcgzWoZ/I4xSbA4ZCW9ige/hkTqLXcv9kIgU6BT/nRM0U6YJqsyHrB7eHTR2wC88W3IfpKaiYzR6sA2gKdYcjJDAfWve/p3k5N97Pyd6NqPYU4yMsaOh/tHBldQl3F4AyDx8IAI9ypw/ZLhs/InZ4aQvcqp6Ts0os8fEm9Ml/zsxDMj8iIknKfTrIaQXV8gfVv5EbQ3uM6fRks95tzXkBPmib2et45e1p/olH+Jm5l/56eQjwi6JmU7sEAnv/sobHscVaXJNGfewV7T+ubp+e9PGx0+zMDX6DPmu/AErmyaym1+5KPHQv+ZS6KOLQasGS2yVw==,iv:0Ba14Yp32hoCzxcHNCSwjZeUMQJojxkiUVlnY8l31qw=,tag:Y5kje0zgLj0xgKJZABTWuw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYM2Z5NUxYeFVRVVdFQ3Ar
        aXJkck1wMUdrcnkwVDF0Q3VGZ0hNYjhvK1dFCk81YmtLTC9wdDVQVkUzUGVCelFY
        aERYb1hKUVZDcTVxcXhGNy9NL3ZmRW8KLS0tIG1BS1hqK1I4Qk1wVnVhMm1PNXlq
        NkRVYXEvQ0hFSTFGQTJXMXZUSkJvMlUKiTAZ3NAfk2QlgYIacrm87lk54c7ekMuA
        y8UwaK7bqbhm+jKRwTys88r9dinjyr1s0fWHGKNHQb+QERliiYrf2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUzRpb0VyTGhGaXFhbjZn
        dXhSY3lmRW1GOXNLeVRkaVNPWFEyMkE4QjJBCjFTcVpsb0ROU3NoZ1hNREpObFQx
        VUp3QStJOHZyOUZQL2RTSFdXeXFmdDgKLS0tIGlKMzVVYU5FbjZxY1E5UnlpSVh1
        MGZYOUcvZzFXYm5zOU5pZEpwVVRxSjAK2UGUPVPJ3BwI4eUv1OWIRiuATIbVyY5a
        VVu0TyfoRmo37IEm/SSqNZRZ3kB72y0R1FCyCrEZ3+EaAiPZ/UtlfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckNzcGpiQWcxL0ZHdGgx
        c0tBSkFpNjVWZE1HMk9WUVRnNGptYnVlS0R3CktIaEdGQ3ZvOTlvaHRMQ01FY3NS
        ZHBYcEMxK0dWYXpKTW5aQjRHaEZ5WEEKLS0tIFJiQWJkN1RJNFZ4cUFRRmJsUUIw
        SW1QWStMVllldEVwNUx2eVJ5Tlo0eG8KuBWx28OTTthY5pdQjeVx115FBrCS/In2
        KiLWiMrHdiTLLP/BVdkoG/Mifxjb+WV58n7nbdOsEp53IffBVmEYBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-02T22:02:41Z"
  mac: ENC[AES256_GCM,data:Am35V14zga3AsPle9pF6pQxC7TiXNyKwi6CepxQFokAVBndPUlYVQ2Mfua4jf3Rx9ju2IoJlR+2FZJi5QU2WzkL6/0JaHvRVCQycj2IC3mQ9zPKTCjgaisX1Us11DnCsbkx2vw8i2u78w527BUit7P0eOwfEwkm5c/yyYZXL+wU=,iv:HbnC/t7htIDwe4P2mvYASUx5K87DIA5fb/fKUUombYc=,tag:WwajOeX1l4/p5HXX4vNnhg==,type:str]
  version: 3.13.1
