apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
stringData:
  immich_secret: ENC[AES256_GCM,data:z9lgId87JB4mKAA=,iv:dc2eTg02YfnSZ/usBkVrzMLtRvLJ8F1rzheNLYSxK+k=,tag:aVSNRhQ8Hkb7SNjRAdfY2w==,type:str]
  immich-config.yaml: ENC[AES256_GCM,data:38NyU5IAg1wYOPle3Xd0Z4Vrt1CZ8a+PMmUhBGMOa3caFbd/JSWEB9aViv859ijQ4SJMufHWq1QLlMqtn8fqyMC2mvcdIgOSyIs8SkTqqw9tGXjFi7vu950AJRoQo00MtZRtr+3BbA/fCIAGlJ81MTsVmUv6DnMUaNnQpEJvOPVtleIs0FSr/AtbkF0pxNdCSYt6qdJs36LwGQ0dplZMY4eM5NKWBUxb9zBrhIr6K5dKdkpfHRK97sM8xs2WMWkANujHOwgU6L2ow29AIilxOJwMkC8mRubtoFyzJQvm04glWfQPU6QxJW4MnSX+YDm6+7bHTvM/KIZM1JAwivzl0jLXpSNq2XVEyj0WBqNvAXGxd6ME1v0ZeCu4fI3SzmnOjSb4gBYekgx+xBsVA4kDE/5ZiDJwObWgBhOGZaJzYh3WivEkjo27crFhH4iqyrCWVANv0kq3YQt34X3zD53ng22UlVZtnWYToEETrNEfbtBqhFymbkCnbxMAdeQIEK84tXkOfaIr8EsozXFCaD7J/9eR+JCLB+m6v8wH9eOSnEILjX3WRPOLTJ28xV9NsHnsLztZ,iv:nlYM1bIq4XNF//F01iz6CSKAd997dO2hoYneAVxBrVA=,tag:7RCfbpeW5bYQnvY7ec6JSg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOWRSZCtobzhqaU9rbEli
        NnNLLytxNTRzT3ZmOFA5L0d4MkRmVXc5RHcwClNYOWNWTTVuSVFVbm5ETUJ4TFJU
        ZUZGQ2pPOExuN0todjNIT3NHbi91cUUKLS0tIGtIT3F1eHRmUUhlQ3ljQUNJQVVM
        UWQ5N0x2c3duanZhb1BaelZnVkJmSlUKBgxKMvRD3sK9+3lN56HJ5YhOHVwDtl5D
        a9Zavt8jEDcS05c8wfzg87X0MwEXnbSvKbSBaAEWzSRY2/vriPbPMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSURnQkllK3pwRDVNdUVI
        VkRFdHZLL1RHTVlXcXJVN0h5cmo3YVRMajJ3Cmd5TGlicThodkRsdi82cWkzK2ZD
        c1JCYmtRTTdvTEc0SHNOVlVnelpjaUEKLS0tIDhxa2lRbUlCQnNSVGdqckp6MGtt
        ZmlkSHVLa1BpSDh1WUZHR2lzVjRTM1kKPjbN8ZECF4jC3R5qZFXE+SQG3XJ5j3Y+
        FMhHz/WR4ORLyGiT8+6orj3uyjwWq7qpjc/Kw78sbrdU83vfj5zSaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQVRPZ2IyNnhiSnNKbExQ
        ejQ2L3RHUExVVUZic3p3OGN0SnhOSUhQR2lzClJ3ekFGc2NFQ2dHK1I2Z1RYbWNY
        eE5rOGx4TFgyUGw0aWRFOG1sUjcrL1EKLS0tIDVvaE5qS2JQaWJ0M1VFMEpYNSsx
        U2Z4bHlvb25BbEI4L1FpWlV2Q0Y0a0kKxlZJK2o3H4f3QiDyV2vesdVKcLMiDVCa
        vVnqOL5OWtOSNnDqJGVbGN5mLJm3Gie/RNKF+6ynNyoPzI6KTbIHxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-02T23:48:29Z"
  mac: ENC[AES256_GCM,data:Rs1dFWf956LmKTkRue3dp9xGkYEqtwTjSoLAHy2sfBSlgxnWjcayCRETDSJUMjS9nSXFLwjnCCJU7U0KvuIer1pBTxwTZu15ytvxAdvwXvp4IuVj6ZVpomj2LhBJW3Dg62ivWXv3MdemcmC+YY8vqvIhoi+EG4oKp1VczVzacQU=,iv:zjp7Aym1X4KGIZsEvIz18bu5FIrI2JubuPY+ChpK1Ic=,tag:FDT6s7+UtML7iG5ksPt9kw==,type:str]
  version: 3.13.1
