apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
stringData:
  immich_secret: ENC[AES256_GCM,data:vcdoceNv42ubyzw=,iv:dZh8ExAoda0vKMplmLmEHF+z9SHsNAmw4tQarVUnuP4=,tag:wvvLaz5wnWsdYNBZP2um2Q==,type:str]
sops:
  age:
    - recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc1lEWUVla0pwYnliS0Q1
        SWw3cTR3cFdJRy9udHRwV0NaWlBoNXIrZDNNCnF4WmxoN21vNC83V2dGSkdiV2FJ
        N1RlazFMVTJsbDNWK0ZZM21FRHBvN0UKLS0tIDU4WVNEenlzSEVJajNsOXZoUFk0
        YVFwQ2t1aTAyajhPaEhEUmFPRXg1K1kKWQtHTFOHTG9R1x/kH4M9m46imsusaLdn
        WeLyRAxLSNonZulLjKGKA1/QZ1ToT0XgcCrgnSGNeAtSpADMXuut8w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVmlmSitzZUljaUtFaWN0
        UkxQK1IwblZNaDd2TGNyNk41eWlESVA4c3hrClNCNFQyazQ3T1N0ZHlDdUNmSXNy
        b2IwZktXTG4xMzI5QkZmcE1Sa1hHT0EKLS0tIHdKaWZQYXhtc09xeDZhT0hWSGtJ
        TVZjbWM3cnd3M05aTFBtelIwdVJYZjQKW1yL50AvWwPdBdtgPJaQIDFe6Sy4RELr
        LtIovlXVfR2yRBiHHOPl0gNbEoruogsXmzPfqNRg+2LKHx3I0zd2QA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS2t0M0tMMXB6d05rMm01
        akcxQkFUa1ZCbWZHd01ZRXNLZ1JLRnM0Sms4CkFYN3B3T3ViOVJXRFpLY3VSeStT
        NDAwTUkrQzJWNExydm11QU5UbTBKaTgKLS0tIFEvTzF0MEdlZDRtSkZJQkhUTFNO
        ZkFrSUc2Q1ZtZTlMMWJCNGhaOEwrMFEKvurwzSk/SaeYBw/kJBcu4cglpN52uvYn
        re3ty1YX383eYOuP2IcQ+/x7zjrPHvk4DCWhateEIToWCYWAZRxR3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-17T15:18:35Z"
  mac: ENC[AES256_GCM,data:1gHhSLBoCTD8F6iXz6U4E06Giv8qgzCmVlj/GuwvRgGv0JrVeagA/JnnziwvwJwbo5p3iLqBIWeYBg+3BnC6srbUVjw4tIQhyMchnkFupYg+JtcUvaYrjXvT5gERvxVvYoxMW/TIDZfrdbQvSN8d2DXJATM4MQID/Dd5hXuuq/I=,iv:4VMdQHOcbcvCJjJcNyTvjF28pUiWHFN3pdiIEdREOYI=,tag:VYlECKhnMBz1+a7ljDRCug==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
