apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
stringData:
  immich_secret: ENC[AES256_GCM,data:j5hcsqeOqjEqixc=,iv:IsDCYjkCVoSDUm5k5MXRXlbRinUnKV0VX4M9U5ryco8=,tag:4vd4mMllgA5mom2ayggapQ==,type:str]
  postgres-password: ENC[AES256_GCM,data:vTg0acqkmhw3ew==,iv:QQYdr/uizTsN3npRDhcLmXukvOc+gDoVHjgVI2y+bMM=,tag:RzJLoQrG7CCYDKm85yJRWg==,type:str]
sops:
  age:
    - recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYWFsdGNMTTlUSTFkNVQv
        T3QvbFhXK2l6K1YxM2NLZnR5S2FyNWpRM3cwClFyUGFwWU5MUGhybWs0a25OaVZs
        dm0rZGZtWElLNlJzVFlxM0dHMlJaYWcKLS0tIGZnQjRRY3JWMjZGNU1wWjBoeDZv
        MExVUHFZeWora0svU2NGUUtGaStxR3cK0xSPA+bnd6c8EBhNsDMkDarlGOEOtxca
        b4Yi15C83Bbb9Zb49Pj+JFiPMvucS4hLNjOs+YGc6pC3Fdmis26zgA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cWo5akZuczNvMlUyalJs
        SkR5ZTRPOVU5WHEwcG9Yeit0SGU0UXRVS2t3CnJwZVlnQlZPTDRNV2JzcENwVmFl
        VVhwMTBpZlVpaStELzQ2Qmo1eTBYK3MKLS0tIDZnZ3hJMUpLbkNRQldEOE1zV29o
        WHQrRzN6ZTN1YmEydlJiNjNrc2lUblUKXqZXfSGfXye+Zb/UfsuxTM+SapM8mHfk
        xBsuGB/LTW8ygliXZO4iLzgUQ2jYX8DdIlwsNHHs7WGJAcDam3LHjw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdkZXVHRVVEYxOTRxM3Zt
        a240NDFNUUZGcENDRWU4VmR2YUFWNjhZMzEwCkt5Y2JRVDBLWkd3ZjhIVktpOEk2
        QUtnUS8rc0pNR0txemNPTklvRklsOGMKLS0tIHpHN2dPcityYzQ3WSt3c01FQVpU
        V1ZtM0Z1WTlUeXBjSm5BR0tRb0wwTlkKl3EWEaxXNjR3GNqkIz9wy+kLsyTwPrkz
        ZCBIUWHsnJ5nu6qL4feewGa8u26en2CB2/rx3bXBStGWMRRuWGDZ3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T00:44:38Z"
  mac: ENC[AES256_GCM,data:qbbcw/uGDvaWuBMo1Vi8NaZXkKCc18smatet0C1QHQZbLv39KPAYeUg1ubljcNIv3MzREoOafgDjuqv3ocSnLoAbYjY39AeKB+g0q05Rycl68aH2NPhfF2NUzS1DAgTVuAOTeEs3EvGdoPRGkpfOxW6WIP1vxlMWAXkh3xCkTYI=,iv:7IChlqo+0l/zqLyZ/TZ42bOEvClPO5xEr39mcKY+mVs=,tag:tC+CMtIviStDUFylvtlBeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
