apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
stringData:
  immich_secret: ENC[AES256_GCM,data:0kDDY8tPVZLJTJE=,iv:nygZpvEdDzWXkBuyb6ks7ohpg1u0NJ7dYc2K3IpKZrM=,tag:2DiRRJz91csGlQwj3Y21Ow==,type:str]
sops:
  age:
    - recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOHNvSG5qOGQ3YVhaMGFK
        MDNBczhvUkNBcWwrNnNjYnZmUzlDZENWSjBrCklLWE1PSWxxbVhHa2sxNFpnbVUv
        UnI0bUYveWUwWTAxeGpDYWlpMXp2RFEKLS0tIHZwVUdWUTc5dWFsVUxwV3NMbEJL
        RGJuYUdlbjN6ZkN0M095dXltMXd6SjQKhshgQWLf03+O67zv4GYQb9faT2Izc7FF
        CubskT1D6QtRD09LGuuGL1j9uTzG3I6OjZ49hGZjy9IDLHmseFwJgw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMGEvWDlIUEdrOVJEdXN2
        dE9BVGNBMDlibUxmc2U5OWJsWkZzMkZoaGtjCnZrdm9KVjVLRFlsL2x4NVdOOXRq
        VnZKMTV5bmtCMGFRRHcvN2lucFd6WncKLS0tIFRhS05FeXhJMElvTUNEZ0x4VHNU
        eFlVV1VUZW5jcitHZENoYjNUTXVYTkUKV2Hhy4ri00lBbcUwYJ0aR8hn1YiK3A1e
        suvcjZIpessUHAmJ+34tqEYT3/y3NqrwKbG21YTZeqkziz4FRHZ30w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzanZXN05ka3J5cE8vTThr
        V2F1dVBSblZBS0ErZEtLaTA5Z01NYkhaeW5JCi8yVXJ4RzZlcHZSNkRPSmV1RGxZ
        T1FkOGRKM0ZTYi9BS0pLdWkvdDVpZmsKLS0tIDRnSyt3bFZOcmVtTmQ4M2hVbWxj
        blRwVXdVdjdRN1ZtOE43cmo3dis5U1EK4mf7toXdj9aCOCwadEbR2Zv35aiwd88T
        DHYYLbwxNYkZTVxGgMIfdHnL/DQWMVMdKUw1f94oIby+7gI7ItFOXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T00:37:21Z"
  mac: ENC[AES256_GCM,data:zvfPuyVtJ4xRMKrRNse8N1PMBoef0qD8T/rpXc8jocQrlqV+auo1qdZZ1HGGKjsqgyFj2/fIkg+FuY64qnQUkLoYdo3qbrUxYjYhSZAp4nJYm9tfDgoWpHZe4lllM6AykY7ouTK8dxJS1K1zdxJSliP2J2fanAGLi9xDfLK6XXA=,iv:7j/xNrjkOCJRmG1rjgc10AOoH1QINvi3OM/l1maFJdY=,tag:zaS1BH61AjyRSkPuiZppOA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
