apiVersion: v1
kind: Service
metadata:
  name: readarr-service
spec:
  selector:
    app: readarr-deployment
  ports:
  - name: http
    port: 8787
    targetPort: 8787
    protocol: TCP
    nodePort: 30787
  type: NodePort
