apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName flaresolverr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *deploymentName
  template:
    metadata:
      labels:
        app: *deploymentName
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/London
        - name: LOG_LEVEL
          value: info
        - name: LOG_HTML
          value: "false"
        - name: CAPTCHA_SOLVER
          value: none
        image: ghcr.io/flaresolverr/flaresolverr:latest
        imagePullPolicy: Always
        name: flaresolverr
        ports:
        - containerPort: 8191
          name: http
          protocol: TCP
      hostname: flaresolverr
