apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Flux Kustomizations
  - ./nextcloud/ks.yaml
  - ./open-webui/ks.yaml
  # - ./open-webui-public/ks.yaml
