# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.1
      sourceRef:
        kind: HelmRepository
        name: cnpg-charts
      interval: 5m
