apiVersion: v1
kind: Secret
metadata:
    name: doplarr-secrets
stringData:
    discord_token: ENC[AES256_GCM,data:DH2n3r+y8/8/xXbxrKuCvyzRbLJYlLt/LasuCOTKOfCOZH6MpnNShRQByFAaas7DyZBnNNbD7WTF8AmtV/vY7YSlnJcNb8bD,iv:buh/z/6i4pWjsC7lDTyFb1gK7gpA06f7b2BSGF/B9sM=,tag:7NGmVyahBbnXEB3Esf3X6Q==,type:str]
    sonarr_url: ENC[AES256_GCM,data:tx8mDnIqYlPVAI3qNFRwtVQsa+hpbB2inCObUEFUvW1Kokk=,iv:RSuZwrVIwQp95iCDWkA0xl2WIx7uP5UJfCTa+saLTzg=,tag:d4i/PzVSDL8iwPLs0g9wQg==,type:str]
    sonarr_api: ENC[AES256_GCM,data:u9mc3Ud2VR0CFi/X8gSM4Gr1R9s3UmwKIGRcCikCb+4=,iv:V7UAy6449afEsxxxh8dwkaniIuU0npxAxIlmtyB+HLw=,tag:mhVeaHAl/6LRUS7xb3vNfA==,type:str]
    radarr_url: ENC[AES256_GCM,data:xGQOKIi312KNEuOpo/2AVR0FtZhdIYO3frUNn4ozOyulguE=,iv:cBUNHdmh4fi2Grk/iSOnWpyGEesUyn4gvRSvGqSfsIc=,tag:6VovUCziRz3gk/zeE4xvzQ==,type:str]
    radarr_api: ENC[AES256_GCM,data:Nt+VhIxYVtpNrlgfcMno/yNEpl0nt9YjsmyYV3Xzr5E=,iv:iR0M+BnMCsCCSPB/cayeIdgOuWmUbWU/gOsugRuJ/ow=,tag:rGuwsW8ch6tCQv1rLesmRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U3VDazBFbkdUanhYSWNT
            T0lKeEduWGtnTFI4aFlicDRna0lNaVlITUVVCk5tMjRLcGtrY1JaY2JISVpUT0w2
            MlhxSVNEaXlmZkg3a0F1VUVPaU16RnMKLS0tIGkyTCt2aW1Eb0hSYUI1d1JRakEz
            OExZKzczZElRd3EyQ1dDWHMzTTJZc1UK9CTpZSZ0G84qUtuvwS05bPCKGVe4/6jn
            mOMKEfKc0DgDrGZ6H4rnHtA2Jpn8PBg094hJ7G4AIf/yzRGOuL75UQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RUpjbzZEc3pjdG0xdUx0
            cVIveEpBZDR2L1dieERoSXVUcEJoRDl3Q1N3CmxTcWZYWkxUdFBxQ2hZQU1QODFF
            OU5oRzhwWEdUU2xBZDVvZFBERXJLeWcKLS0tIDhrR0ZSSmxvSnpDVkhULzJZYkli
            aWdkQjA2L0RtajA3dGRnMGhWeWp5MDQKS1eCYKGK/EMzCYAWJM/1whyutbUA7GjN
            kcvKZSvJEKbQ+u2RvN/YtCM2FNUKlxZDuzXO2137HP3SOrIRhgdo1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t067r55hvu848a4s92d2dn97xu8v8frcszh6403gsrqrkayp7f6sddhdgh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSkJpd3N1Q1ZqMjB6NVVv
            L05sWkVVa3Q1QVpYbG4vYk1za2pyYzBQL3hrCldwRWtMcDZkdVI3bzhiQ2dZS1o0
            RmpiLzZyVy9IeTdiWkVncDFJcU55MlEKLS0tIDk1dWloV3pnUmJpa0hlcG15MHdk
            ZXdXNzRQRDUzUm1KOFFxQ2RjRVpXZW8KRiLx+1plLyOS8Tso1nFFdSjLmld1Hf8e
            UlQ5oChWqQL+SlELRAgwyisEIjrbppylHxwdmccrkNTlmYYzKT9NwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w3jq4l9kaka6kx8pazvykv077dajde0qtgnsyeukgfcksu0w6epsltys44
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraXpGUEkwd0pmdWZEeFdC
            SktGVEE4azJYczJFQytYTG9pT2E1ZEhEREZzCjZScTZkbVFqcWtmazdyczRjRGF1
            Y2daWGhKV0wvUE9aamFjaGtXTTNSNU0KLS0tIHQ1ODAwQXduZEI1cUc5bmx0NWhX
            MnBuNHpLejhxek05SWo0dks3eEh2YW8KgeKGi1mzabuDsM1osoACgwoWWgwr6g2O
            kxkuM9sLx0/BpLc/eKhmVj1lWFIhDvJvcJuaXeSuefnPVMwWS5Bwqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T14:37:13Z"
    mac: ENC[AES256_GCM,data:SRScQOjOZgB4omTBnziQLUZoura/fJsULgCus7Tz886IqiZADuK9xrlEzG1uXzoS4rPw9toS04MkaMofs5A5R9QCbyF/GwV8TJqVZ44sTyxzNaekQFNWTZnocXkgKzYgiI6uKKB/Ao8vWFlO/S+NcpEKLkh9RcDSvsL+2cZ0/wU=,iv:fbkm2TqCXdl/SG9cMfwLHjbWjKsyFONefxbT2VPNiCQ=,tag:9ZcNmDWfFz15eCZOILX2Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
