apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName ollama-webui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *deploymentName
  template:
    metadata:
      labels:
        app: *deploymentName
    spec:
      containers:
      # - env:
        # - name: OLLAMA_API_BASE_URL
          # value: http://ollama-api-service:8080
      - image: ghcr.io/open-webui/open-webui:main
        imagePullPolicy: Always
        name: ollama-webui
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      hostname: ollama-webui
