apiVersion: v1
kind: Service
metadata:
  name: ollama-webui-service
spec:
  selector:
    app: ollama-webui-deployment
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30280
  type: NodePort
