apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  DOMAIN: ENC[AES256_GCM,data:55v4szUZLEW6pcdQ73o=,iv:th96hwmwE331gv87vOImZsCsOQI7jyIW0uNQ86a+zH4=,tag:dZger/bBYBu0rWL0Qy9Hbg==,type:str]
  NFS_STORAGE_HOST: ENC[AES256_GCM,data:33Ov4Via2S4oBK7D4OZpwuqEIrBOkSrFXiCbQEvgIPbjoaag0Q==,iv:90aiFsPyjuJEs3mv/C2vNHh5SMJyjw4He8tCnLKLxt4=,tag:ojk1LUkjp+NBCI4Q+4rV7Q==,type:str]
  NFS_STORAGE_HOST_FAST: ENC[AES256_GCM,data:upH80ji9qPFyEi7Fyb/FOJLKc5WvpCF+9Ed12+pPDAfw+V5FODMUDU/Vwy32,iv:w1IUwDc3fpxPcV6DtK72vjY7D6Z77L/Jf9CM+7A3ZU4=,tag:OMZmrawrX/SPtNaJ5oKotw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRWNiajgzaXcvbkRFSFpx
        b1QzdW5wQmdTYitVb3F0SnZXV0w5L3hPWFRZCjIwUGFUYWd0NjBSTUJkRDRRUXht
        V2VaS3ZPeG5ibXNOcVNYMElCaWdXSDQKLS0tIGNXUzNkSmtSTDdtOFI4YjVwY1Bs
        dnNHOXJESmpVdENwN1dnU041YmNJQ1kKDw830vdVy7YK/XCtdrg9Lmwx9I4zvcJu
        krgoyuFmhxbXmsYxvmXyh7iLtUArUWCclZ6qZ/IR6qpKd7zO1feZKw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMm5sL1pZcnZ2YnF5MDdJ
        WlIwNmJPcXhiektpdVVibnppMmlzNDErK0ZFClkwWXFnNEpGYnNuUm1lQTd0VUow
        Q1RIVTc4bnhRN2tUVUM0Q29xbVlvWWMKLS0tIDNTaDRybzFZZVhIN1U2N0taTjZt
        YkJqYUswZWROMnJUOVpOU1lYNU81dVUKyrPviVZj1yo/3MP0dRQ59Zb/UzRhGAwD
        Xciok5mbBWEnIQhZTEvfXK55nb8m6xHChOsVDB/3mel/I40eALZYRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4czB6aU1XU2p4S3NLamUz
        bS9wUzlzLzRyMzdla2pNbWRzQjlkT09Xd2t3CnZpVVh4dEFySjBjNVpOTkppSFJa
        Tk5mN3Q1MWxmSHdqb2hmQmQ4cFBWQTQKLS0tIFg2V1l0U3h1UjBjL1drZkR2NjZP
        MXIzVnVPRDJVZFFVc3BCd2F5S3gySlEKYZjbESDs9ZV4pAgRZKUbqa3TiGrweQrm
        nGD7tXS89EuWbJO9ukvjgYp7ymd0rjJqLxwn9gnTU0l1LFEoN2ombA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T21:57:11Z"
  mac: ENC[AES256_GCM,data:Ysce6B+WGZ2UwVrmoG03v80SaQDsAhzPM3z5nlN7Hu90jtamPw+8gyucnEKoMnFIpuS/DjGSh4A6Akjo0571Q561U6++AcCzfpty7pR8TUEYkc+LrCTWS0ZjOehONIsM0wsgPmBWVU+dDbE8yA4mYbxPz2eY+hLwfsVONnjqLHI=,iv:bzhiANovDBP8uZr1Y3yyOIZt+jxxNiZ0OZFGLhblO/g=,tag:5sN7GB1dkFr4U+RhtTOSpA==,type:str]
  version: 3.13.1
