apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  DOMAIN: ENC[AES256_GCM,data:nw283iETCzRTsgLu6DY=,iv:KGfngw+1k39wdXHmYUQsBc6a7cf77RYpZaO4AvXc770=,tag:NwFtjBaPvCIGP/ZP74BplQ==,type:str]
  CF_DNS_API_TOKEN: ENC[AES256_GCM,data:uoRPnbQWvmO0DCrblcZON8ffU5ixdcvwfb+N728AclZj3EtDbZpcdg==,iv:HwXP/nHUMhFCZurr6t3q2ehFiR+8dRc9gwOq8nIwRJM=,tag:4eHcFzM1E3IXKZt9JQdDzg==,type:str]
  NFS_STORAGE_HOST: ENC[AES256_GCM,data:L7WP+LVJnq4Ff75Vf+ZF6vRWsa+tlFMLT7Un8R6W/Opy87e54w==,iv:e3ZsCYDWqaawrQnB367e9dmRuJyUnT8pLLq3b/Wd/L0=,tag:67zVMdsJ/juOnRSpLH/6xA==,type:str]
  NFS_STORAGE_HOST_FAST: ENC[AES256_GCM,data:20T93Mimq7m3ew5lh74cMlm3sovNMO5KPRHWlfPYQqY+K5qMoaAIn7/3ifBE,iv:o03XOg8Gkx4BBHmL/vhZ5mqFrq/G+XkN/YXdeGf19uU=,tag:+NSAzHeb4qTquafyEAufXg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUFZrZG91aTJTVjdqb3VL
        dE9rRi9WbEJoSzV1aFVyTHVvRlVxWUF4aGg4CkhwbllvdHNrWVRCTkVDRlo0S243
        QkFNV1BDcVcxTGh5ZXF1WUhzNk4yRU0KLS0tIG5PUncwSHI5ZXFuS0dTK1V6VWNM
        SmpzdXRtUkpsSXRzdWxyeHBLZEZPem8KdL8KJFzdvdh9eBtyXMM3Gze4XJKJ5Ngb
        t+nMpLueSrpJcz+g6J2QTvUUzEuVhrJTyftLrrklTYQ/0Gh9cfdJ/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZG13ODhvcm9CRG1LbVkx
        bUpmYUVCSzNWNnY5YS9tcXVINHRsaVFBYjI0Ci9PTmxEN0xHeHRVMXNidlY4bjNW
        ZXJaMy9nT0JSWGs4azdTdkRpc3pRczgKLS0tIEJUN083OGlsVUVVQnVoa05yYkp6
        SXA1SEhQN1VXbzR1UVhKTHVGVWxWSHMKOJXCgHLnr8Lj16ljiqRy5LO/YMPd1Xcz
        OD8vKhDycv17W1Qks8ANJt8QM0hoOjQjGWW+0wLjpxfOZ5e+T35zxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aUhuSlVKSlZIMGhncmtR
        SGQ1bC80SXpGVDlUY3lud0VuazZHalprMWdrCjFFQzU0d1hkYUtoQXh2K05tNWxD
        bDh4Y1RTQ3RzeVRGVnJvd2YwbGI1a00KLS0tIHZLNEtpOXlRWkErc3ZCdG1hazFU
        ZHBMWitNei9GSlVZMGpTc2tMTlZyVncKZQ7aaLqwa0fV2EhDPP3OR2dAOON1Kh97
        6dJ6kqGcpBtl1xjSF5zZp6npY/PV+u1kh5HM6SZME7rVC+dovOjYWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T17:31:13Z"
  mac: ENC[AES256_GCM,data:0jb1QwCe4v+pn8BjlQWP3L3iVuW7cjGYA22W5rKfrtwXbF9LVivWYZwIYE4eV43AJaVEeEtO2+WGPGXA3PkXiOtEAUUHMqc51K9rUXooNio1ZJ0h0nu1lhuZFZVAHDn3uarJ17IPUUI9eU2/PgYsUxJb96KcZGlvsEGg8N9Dqjs=,iv:RkgQIIlFPmbeH9dH8XZHt04VZXd0GKfiOZnwGUWJlTM=,tag:Q5RwxwkGiRlgpfPc0ZiRZA==,type:str]
  version: 3.13.1
