apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  DOMAIN: ENC[AES256_GCM,data:nw283iETCzRTsgLu6DY=,iv:KGfngw+1k39wdXHmYUQsBc6a7cf77RYpZaO4AvXc770=,tag:NwFtjBaPvCIGP/ZP74BplQ==,type:str]
  CF_DNS_API_TOKEN: ENC[AES256_GCM,data:4ZGnEdYLqyhihqSKkEOAkpfGmdnJ6KOvOULqBPNQMB/2NKbu3gMG985o6g22KDkJwdx6koB0eJNP4xu/m4cRvQ==,iv:ls/+TmMlND6OuFm2mBsvWfbOzuFXlVusN5HH8o5vlTw=,tag:4LXHxwnbfvPMQ6ue7obGDw==,type:str]
  NFS_STORAGE_HOST: ENC[AES256_GCM,data:L7WP+LVJnq4Ff75Vf+ZF6vRWsa+tlFMLT7Un8R6W/Opy87e54w==,iv:e3ZsCYDWqaawrQnB367e9dmRuJyUnT8pLLq3b/Wd/L0=,tag:67zVMdsJ/juOnRSpLH/6xA==,type:str]
  NFS_STORAGE_HOST_FAST: ENC[AES256_GCM,data:20T93Mimq7m3ew5lh74cMlm3sovNMO5KPRHWlfPYQqY+K5qMoaAIn7/3ifBE,iv:o03XOg8Gkx4BBHmL/vhZ5mqFrq/G+XkN/YXdeGf19uU=,tag:+NSAzHeb4qTquafyEAufXg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUFZrZG91aTJTVjdqb3VL
        dE9rRi9WbEJoSzV1aFVyTHVvRlVxWUF4aGg4CkhwbllvdHNrWVRCTkVDRlo0S243
        QkFNV1BDcVcxTGh5ZXF1WUhzNk4yRU0KLS0tIG5PUncwSHI5ZXFuS0dTK1V6VWNM
        SmpzdXRtUkpsSXRzdWxyeHBLZEZPem8KdL8KJFzdvdh9eBtyXMM3Gze4XJKJ5Ngb
        t+nMpLueSrpJcz+g6J2QTvUUzEuVhrJTyftLrrklTYQ/0Gh9cfdJ/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZG13ODhvcm9CRG1LbVkx
        bUpmYUVCSzNWNnY5YS9tcXVINHRsaVFBYjI0Ci9PTmxEN0xHeHRVMXNidlY4bjNW
        ZXJaMy9nT0JSWGs4azdTdkRpc3pRczgKLS0tIEJUN083OGlsVUVVQnVoa05yYkp6
        SXA1SEhQN1VXbzR1UVhKTHVGVWxWSHMKOJXCgHLnr8Lj16ljiqRy5LO/YMPd1Xcz
        OD8vKhDycv17W1Qks8ANJt8QM0hoOjQjGWW+0wLjpxfOZ5e+T35zxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aUhuSlVKSlZIMGhncmtR
        SGQ1bC80SXpGVDlUY3lud0VuazZHalprMWdrCjFFQzU0d1hkYUtoQXh2K05tNWxD
        bDh4Y1RTQ3RzeVRGVnJvd2YwbGI1a00KLS0tIHZLNEtpOXlRWkErc3ZCdG1hazFU
        ZHBMWitNei9GSlVZMGpTc2tMTlZyVncKZQ7aaLqwa0fV2EhDPP3OR2dAOON1Kh97
        6dJ6kqGcpBtl1xjSF5zZp6npY/PV+u1kh5HM6SZME7rVC+dovOjYWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T17:21:54Z"
  mac: ENC[AES256_GCM,data:33bverTpIWEIMASdCLRv5l+TBW53LVwUP5q7/YGjxlATPyez/XKQZzj0dWUHyFe//x++ywCcmJxCzqhGY/+pyYEgXZ6eIVzF0Twm1nnnsEIoiRpRwlc1RoCOi2PmYqJCQQESy+67s+SILY/pRrG1ZZr9jcyD7mwDqpldG3uCoPM=,iv:ScKTxsz8lEc827D8wjQ8waVFvjVLpGWaUVYDtgXNI5w=,tag:oUUxu2O53B7Z8R2PA46vwQ==,type:str]
  version: 3.13.1
