apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName nextcloud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *deploymentName
  template:
    metadata:
      labels:
        app: *deploymentName
    spec:
      containers:
        - image: nextcloud
          imagePullPolicy: Always
          name: nextcloud
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: config-data
              subPath: nextcloud/config
            - mountPath: /var/www/html/data/nfs-share
              name: nfs-data-volume
              subPath: productivity-service-datastore-pvc-b065dfc6-440b-4b9e-9b3c-b4d705e90bcc
      hostname: nextcloud
      volumes:
        - name: nfs-data-volume
          nfs:
            server: ${NFS_STORAGE_IP}
            path: /mnt/mopower/swarm-data
        - name: config-data
          nfs:
            server: ${NFS_STORAGE_IP}
            path: ${NFS_STORAGE_CONFIG_DATA_PATH}
