apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-deployment
spec:
  template:
    spec:
      nodeName: knode3
      containers:
        - name: transmission
          env:
            - name: DISABLE_PORT_UPDATER
              value: "true"
            - name: OPENVPN_OPTS
              value: --inactive 3600 --ping 10 --ping-exit 60
            - name: OPENVPN_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: transmission-secrets
                  key: openvpn_provider
            - name: OPENVPN_CONFIG
              valueFrom:
                secretKeyRef:
                  name: transmission-secrets
                  key: openvpn_config
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: transmission-secrets
                  key: openvpn_username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transmission-secrets
                  key: openvpn_password
