apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-deployment
spec:
  template:
    spec:
      nodeName: knode3
      containers:
      - name: transmission
        env:
        - name: OPENVPN_PROVIDER
          value: "PIA"
        - name: OPENVPN_CONFIG
          value: "uk_london,uk_manchester,netherlands"
        - name: OPENVPN_USERNAME
          valueFrom:
            secretKeyRef:
              name: transmission-secrets
              key: openvpn_username
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transmission-secrets
              key: openvpn_password
