apiVersion: v1
kind: Secret
metadata:
  name: transmission-secrets
stringData:
  openvpn_provider: ENC[AES256_GCM,data:Jp7dhDg7mCei,iv:SX1z3hgUUz6RVPxd8nk9+Fne+5CBIEg3OGmpaTP7+/g=,tag:K3+2E2d8HVSF/0ELEs5lzg==,type:str]
  openvpn_config: ENC[AES256_GCM,data:jmvEe+Kr3Lv1YPHwNc/R6/u64DGkGGVaWnwNStC/5zEvY3Z6BEtyyAnyQ9PTE99KohQ=,iv:wmkND/1knH63SE6fl9i1RXJKRW9QIPUkWKpkHbw8Xvs=,tag:vEQ4IX0xWD+81FiY8CjeNw==,type:str]
  openvpn_username: ENC[AES256_GCM,data:1G7PqrTA0LiytF43EbFnc7LxpAQ=,iv:cycIEdxlmA9dht2PeAqp0cqCLbFsCm5TzQF7AtNmqTA=,tag:iuG9j2nUIYfxv1nRsq5U2g==,type:str]
  openvpn_password: ENC[AES256_GCM,data:qV197KtvhnLVDARK4BelYz1cgbWo21ckEURLSIJvqsQ=,iv:g96PA4Xtb9y6VUaftc+qqIF3QTaT59meHPZNyaPLXgE=,tag:mPa/LLnUW+2//D5nmJ+7LA==,type:str]
sops:
  age:
    - recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxa053TytuWGkxZGVRS2VP
        R0pkaFVUUXF2cU9KS2w1TTdvdEFZamE5cVhnCllKanVPK0wwSWNGbVZIR09tUDcz
        Q1lBQ1ZwTkNTb05OdDI1YjQ5OXlGRkUKLS0tIGhLRW8wVE5oamlQQ2JuVVRoRWZG
        MmNGZlNhbitOR3lQNFVhb3VxSEVpNEkKvrHfOgvezhFmqkGntcp6ydSCrQa2m1LM
        OUbibz+1/IzvecyOnBhr4MPCRm6Uhb7Kp3bHv3IK77XU5LLyvYk87g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cjVYZElQRFY5N1ZpTkVo
        aGlvY3p1a3RUQytaZkZkUjZoSHg1M2hCS3dvClRSK2h6QWZIb3ZSKzJnZU1XYk4y
        S3JFRHB6Q09yWTBBNVlocG43WTVDcEEKLS0tIHhQNk1iQmRnc2MrOXN4QlB0RlIv
        ZGN5Z0JYSUYxcmxyNzMyS1BuWVdqbW8K3tgkf9pSSLXdz3AxyTL7dY/R1UDDjeOx
        gl9BVjrFIYj5PpbAGY81jQKNL8SD2qujkgZdfeTy3Fy1cRNKz+eddQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1t067r55hvu848a4s92d2dn97xu8v8frcszh6403gsrqrkayp7f6sddhdgh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MzE4WnNXL2pXSnQwTXpN
        ODJVdk9MRGY3ZzYxMzVBSlNab1lRQm9KclJRCnFvVmo5TzFERC9ESm02dXRYZ0ov
        VmE0TUNVc2RPSUhrWnBiUlFpcGlOQU0KLS0tIGMwWFJtdDRjNEYzY0Q1UE5TR1p3
        Z0lTYWVEemdzYkV3Q05OZEJSWEFLdm8KwpTZU1MaT5kiQszERQGL2Qwru43qhviK
        7usBfjFAcNYbCFlKKqU3G2NLRGFesYuUWIU/5ZoqAPc91P/nm60OEA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1w3jq4l9kaka6kx8pazvykv077dajde0qtgnsyeukgfcksu0w6epsltys44
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQnZvZXdQV0dEdUZTbEc3
        Qlk2d1pUNFlTRjdOTm96WnlXd2hORDh4THhrCjd0a205N285dTBYTmw2UXBWWDA5
        dnJLQ2RmK0UwQmpJeEl0L0ZTc0tsSWsKLS0tIFZMYm5tallPbVVxTEdpY09hOERB
        YnR0Z1ZHdzFCNFl1VVh5NlFzRUZOSVkKSPUrCQA2Ee4mTAVsL3PupAF7J2wAni31
        DQcRs/n0Ayg7rTyULOBJXP6nfrx08/seT/bJ96S6c0cIgJAhlbjW1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-07T09:40:20Z"
  mac: ENC[AES256_GCM,data:07F4zpc5e8HtNfGVTB17ud7afF3Hfyf/qcqy8MDenjQRrVYnMQQSZsQ3Z5BvJDkOldG/H6t3arYhICfVa8mongKwO5mAlePzGV6vw3Jf8KhKO5EMHPiZWzQ5b69b7UDcgiQq/sowVTg1+ecT3FcKYgFjJcHVuMVXAg9MjD4QOxg=,iv:2IiTUMi21FPYPyvPWPfUiwjG5ymG5b9Bmd8LaK1XuX0=,tag:Pg4ywYimLrbW98qd95u5dA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
