apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "25"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.0.1.42","10.0.1.43"],"port":9117,"protocol":"TCP","serviceName":"media-service:jackett-loadbalancer","allNodes":false}]'
  creationTimestamp: "2021-11-24T00:26:00Z"
  generation: 95
  name: jackett
  namespace: media-service
  resourceVersion: "464813070"
  uid: 77741061-be8b-414d-94e0-c99c001fb140
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-media-service-jackett
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2024-02-07T22:14:23Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-media-service-jackett
    spec:
      affinity: {}
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Europe/London
        image: lscr.io/linuxserver/jackett
        imagePullPolicy: Always
        name: jackett
        ports:
        - containerPort: 9117
          name: jackett-port
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
          subPath: ./jackett/config
        - mountPath: /downloads
          name: downloads
          subPath: ./jellyfin/downloads
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostname: jackett
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        nfs:
          path: /mnt/mospeed/swarm-config
          server: 10.0.7.202
      - name: downloads
        nfs:
          path: /mnt/mopower/swarm-data
          server: 10.0.7.202
