apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName transmission-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *deploymentName
  template:
    metadata:
      labels:
        app: *deploymentName
    spec:
      containers:
      - env:
        - name: OPENVPN_PROVIDER
          value: PIA
        - name: OPENVPN_CONFIG
          value: uk_london,uk_manchester,netherlands
        - name: OPENVPN_USERNAME
          valueFrom:
            secretKeyRef:
              key: OPENVPN_USERNAME
              name: transmission-openvpn
              optional: false
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: OPENVPN_PASSWORD
              name: transmission-openvpn
              optional: false
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1001"
        - name: PGID
          value: "100"
        - name: TRANSMISSION_HOME
          value: /config/transmission-home
        - name: GLOBAL_APPLY_PERMISSIONS
          value: "false"
        image: haugene/transmission-openvpn:latest
        imagePullPolicy: Always
        name: transmission
        ports:
        - containerPort: 9091
          name: http
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /config/transmission-home
          name: config-volume
          subPath: transmission/transmission-home
        - mountPath: /data
          name: downloads-volume
          subPath: jellyfin/downloads
      hostname: transmission
      volumes:
      - name: config-volume
        nfs:
          path: /mnt/mospeed/swarm-config
          server: 10.0.7.202
      - name: downloads-volume
        nfs:
          path: /mnt/mopower/swarm-data
          server: 10.0.7.202
