apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config-data
          nfs:
            server: ${NFS_STORAGE_IP}
            path: ${NFS_STORAGE_CONFIG_DATA_PATH}
        - name: nfs-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-shared-storage-pvc
    initContainers:
      - name: set-permissions
        image: busybox:1.36
        command:
          [
            "sh",
            "-c",
            "chown -R 33:33 /var/www/html/data/nfs-share && chmod -R 755 /var/www/html/data/nfs-share",
          ]
        volumeMounts:
          - name: nfs-data-volume
            mountPath: /var/www/html/data/nfs-share
