apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-oidc-secrets
  namespace: productivity
stringData:
  oidc_client_secret: ENC[AES256_GCM,data:U/De/GnSZ3Vp3VNjGio2VH0AYctGUTpaaEJnGnvaEd7cGXoa3VCz3xoELl3GgKLvkGJi7nWcv6/kd6/TpJghpg==,iv:RH8t/qA/s5CF/BgI6RHzvPZHsk6kGXunht5LqKMwglQ=,tag:BNSLerfc7cw3UV2z8pEtgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS3RRWk1wcW5MRTFKVWlT
        czZ6ZDZ4R1JYWk1MNW5Jd0NWazROejNtZEcwCkFOVWw2bTJabEd0bjZ5cUloNlJJ
        U21RK1lpRGlSWW9EUVZtTkllRTdTUjQKLS0tIDloYll2ejZmVEtqejVnV3VsOG1a
        ZWF1a0pqUnVjUEdjeDMwdGRjdHJ6YU0KrVlfrx2rd84ZGnhYO+5XUbWLz+X7n/WJ
        bQcSf8PLEA9+bnZFPguxwGnoiRt2PpW1OweKKNWx4JjtiuoARxLdXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVGFWWkhGYkZRaUlTMjlT
        Qjh6eXgrbjBuM05vRDAxN08zRWNONUcxdG04CmdQLy95L0YxejVQYmFkdTR0Y1Ft
        dTJkb1dXcFJUa1dvUlBKb0xrakJRZGsKLS0tIFlxK29JKzUzTzFHSHVIR29BZ05u
        N05kTDhHUDR3d2VKQUdYeUw0WXlSMkkKGtQ4fSujoRSqLsaOHPHtwBVUoSbYmClZ
        2b0ROkKzsVXc4QoMYuRcUeedS9XOcYCOg6HUR7hkVgicrlk6RUn8hg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOGQvcnE0aXA5bW0xT09Y
        Vmx1OVc2ZW5GZGZpRjFuMEpsVkJ5aE8vcFc0CmlNSnJXekdOOUdIbWRFYVlTUU1F
        ZzhyVnVmVW1SSldKYnlkNWZyaGk3R1kKLS0tIFZMSzNRVGlmeG9UOHBXbGYwUVNH
        aUdVaWNCS0FQK01aWGtJZU0xMHF4bnMKad6IyXJybzz+c/2pUX97jc/gFGRin/0Y
        C/xUEOFpV9CJLHuPyuyEXsTFQYAI5K6sL2TM8J4ogcWb/615OQ/pXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T00:45:01Z"
  mac: ENC[AES256_GCM,data:kSNf7P60OWDSudJYVD1JhDPSLoAkGo1tVsERFfS6xC9BkAGloH1a/RkeJMXuOx5qOYPuJoNPGMbTBdbKljKqqkstNr0MdOcq9+hWvoEuDTLEhJ5GvvjttWgos68/7KNpWvWhVcRMBg8LkXfUTMSsLoCWvNWL8KzkYw7mohvuOzM=,iv:EJOxyDW+ThQIJ+JnG4nHof2dZLVjEITKN+ORsWjTNEo=,tag:fHSsfMLqgOVHs8Y7nPYpVA==,type:str]
  version: 3.13.1
