apiVersion: v1
kind: Service
metadata:
  name: requestrr-service
spec:
  selector:
    app: requestrr-deployment
  ports:
  - name: http
    port: 4545
    targetPort: 4545
    protocol: TCP
    nodePort: 30545
  type: NodePort
