apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-test-media-service
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: media-service
  path: "../../../base/media-service/nginx-test"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |-
        - op: replace
          path: /spec/replicas
          value: 3
      target:
        group: apps
        kind: Deployment
        name: nginx-deployment
