apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-test
  namespace: flux-system
spec:
  path: ./apps/base/media-service/nginx-test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 10m
  timeout: 5m
