apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-deployment
  namespace: flux-system
spec:
  targetNamespace: media-service
  path: ./apps/base/media-service/nginx-test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |-
        - op: replace
          path: /spec/replicas
          value: 2
      target:
        group: apps
        version: v1
        kind: Deployment
        name: nginx-deployment
  wait: true
  interval: 10m
