apiVersion: v1
kind: Service
metadata:
  name: hermes-agent-service
spec:
  selector:
    app: hermes-agent-deployment
  ports:
    - name: http
      port: 9119
      targetPort: 9119
      protocol: TCP
