apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
        kubernetes.io/hostname: knode4
      tolerations:
        - key: dedicated
          operator: Equal
          value: gpu
          effect: NoSchedule
      containers:
        - name: jellyfin
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
              gpu.intel.com/i915: "1"
            limits:
              memory: 1280Mi
              gpu.intel.com/i915: "1"

