apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
        kubernetes.io/hostname: knode4
      containers:
        - name: jellyfin
          resources:
            requests:
              cpu: 100m
              gpu.intel.com/i915: "1"
            limits:
              gpu.intel.com/i915: "1"

