apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -production
resources:
  # - ../base
  # - ./testbench
  # - ./monitoring
  - ./media-service
commonLabels:
  env: production
