apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wayom-database
spec:
  instances: 1
  storage:
    storageClass: nfs-csi-default
    size: 4Gi
  bootstrap:
    initdb:
      database: wayom
      owner: wayom
