apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr-media
  namespace: flux-system
spec:
  targetNamespace: media
  path: ./apps/production/media/sonarr
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-configs
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
