apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - secret.yaml
  - middleware.yaml
  - middleware-redirect.yaml
  - ingress-route.yaml
