apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: network-system
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:ZtctA7/7K4nQg7DbKRbidjHMJWbXQFOAH/4KOm9TuyT6h0I0wClOiw==,iv:ZB47xoinxb6duBGuuvtWMWXlTCCgdGsJwBpbOsYFMDg=,tag:S0r8XPjLULVCpYc3RBb9jg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YWJlWXdzNlZzYVE1dFEx
        WGd0VnJpQUw5aE5OMGo5RDdmNHNFWjlER3dVCm1aQkdPWk9ZWUp5TEh6c3B0a2ps
        S1A0cWdRb2FTc21oVjBLS25ZOHdJa2MKLS0tIFROMVpTRmVwYmhHQmZUSWpWNXdq
        cXhXeDNHMlpqclhwVnBPRXhKZ3JuSWcKJT6UaVRcXNxb+dGJrE5we2uCaf5HpFqY
        ON8GfFuj9O8KC0RoztsU2Yit7378xOb+4XrN2UShcg3nrecirgzhXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eXZBWlVka3ZkVW5SdEJx
        WC80enNTcG1nNS9rVE01ay9pdkcwRWU4ZFJVCkE4YjZPc01nNnJ5a051TkljYjgr
        dVVoU1ZQOU5CRXFhUmVCWlZmbkp2UEUKLS0tIHptWkUwaHpWVUJuQXMwbFo3dXVu
        V3V6dGxvcHVlSVgvNWdSNnRYTVpiNm8KpEHl+9zNSZwLnajWA6JbtnSCUayrfUZA
        UBOJbUJpyObvg8sp2lUTJF9cwtk2ryLJ1uf4tk3ejC+wh3L1zZlcMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRlhrdDZMYUVxYmp1ajRB
        M29lL1RRemhqblJGMldUZ1MzdjRkU0YwdFE0CnBVNXlmWUVwWi9rbUREZFZ0WXdH
        Q0R1U2JUdDlOTVFLSy9peU5oS0NYWEkKLS0tIHhIR3Q0YUJaS3VXeEUzOUowNzFD
        Qzh1Y3ZOTzQxWjFKbGszYlpTMWRRckEKtaF+xzOlZsO8S4H7/uxe1ezPlj0cBaaf
        OoHsZJWSqiRLam7Pp2BUlPxVDnL4LFcxuW4ElmGC5J0G55rmJDG0Yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T21:57:11Z"
  mac: ENC[AES256_GCM,data:pAXVgtT5X5Gl5vCz59vbV4Fq6T0kCzPORDoerdUG7E2hT0vtPoPlFtXBKEkbnGdrNohdZrz6YUmJpYNEfpgZuuzz315EqB8u2qsrHrvU4Uecn5PLcOdhHxrulJ0fvXlee2/gu6tC/lPRh0aeekTuBpEsRTZyue13sbdcixk5GJg=,iv:CPZLoWydf9gdi6KGf84qqTRrqJRc2d5DQUAMfsmRj9Q=,tag:KgyCyd70xolHYhZo9ZopPA==,type:str]
  version: 3.13.1
