apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-deployment
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.8.4
      sourceRef:
        kind: HelmRepository
        name: immich-charts
      interval: 5m
