apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich-charts
  namespace: flux-system # Helm repositories are usually stored in the flux-system namespace
spec:
  interval: 1h
  url: https://immich-app.github.io/immich-charts
