apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`chat-internal.local.${DOMAIN}`)
      kind: Rule
      middlewares:
        - name: authelia-forward-auth
          namespace: network-system
      services:
        - name: open-webui-service
          port: 8080
  tls:
    certResolver: letsencrypt
