---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: open-webui-productivity
  namespace: flux-system
spec:
  targetNamespace: productivity
  path: ./apps/production/productivity/open-webui
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
