apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
spec:
  template:
    spec:
      containers:
        - name: open-webui
          env:
            - name: OLLAMA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: open-webui-secrets
                  key: ollama_api_base_url_local
