apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
spec:
  template:
    spec:
      containers:
        - name: open-webui
          env:
            - name: OLLAMA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: open-webui-secrets
                  key: ollama_api_base_url_local
            - name: WEBUI_URL
              value: https://chat-internal.local.yomitosh.media
            - name: ENABLE_OAUTH_SIGNUP
              value: "true"
            - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
              value: "true"
            - name: OAUTH_CLIENT_ID
              value: open-webui
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: open-webui-secrets
                  key: oauth_client_secret
            - name: OPENID_PROVIDER_URL
              value: https://auth.yomitosh.media/.well-known/openid-configuration
            - name: OAUTH_PROVIDER_NAME
              value: Authelia
            - name: OAUTH_SCOPES
              value: openid email profile groups
            - name: OPENID_REDIRECT_URI
              value: https://chat-internal.local.yomitosh.media/oauth/oidc/callback
            - name: OAUTH_CODE_CHALLENGE_METHOD
              value: S256
            - name: WEBUI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: open-webui-secrets
                  key: webui_secret_key
