apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: productivity
stringData:
  ollama_api_base_url: ENC[AES256_GCM,data:Oz/HY2Ez1j638wCVBb+RvSoqGXBj0QX2oLIDYq44gQ==,iv:dXDrvUJzG7W92x7DanbMhKNk7bzQ06N5k1SdQXj1S/I=,tag:HCE9Jfz73hkvYeQSpRITOw==,type:str]
  ollama_api_base_url_local: ENC[AES256_GCM,data:w4pwY7pBAa3jxGpxx2CRV12lDlCL4budnDV+GySUmtQEASn6iA==,iv:0rs8QcMxbZ8d8SAMFJ8y3NjsUA+DMibFuDmEQsRFh80=,tag:cuR42Kx4YHeGf+okawgjYQ==,type:str]
  oauth_client_secret: ENC[AES256_GCM,data:qf/PIVnTulqv9xP6a4jtqeK2R4ouuEwREeXM5gP+dcYkYI2iJ+IApYdLQ2tfhqMNiwUOUzD9osj9vVGx4QE2xw==,iv:JWxM07NuXwtDTST8H8PXNbSyzLJsvF12JR4DHmAzQLE=,tag:tKO8GXVrAAbnClu+L9dF3w==,type:str]
  webui_secret_key: ENC[AES256_GCM,data:RXKVSvHQenpN1klwAPB/rtPtztE4o3ju5lEp7ZZTVlE5uhVo8eVl5U7zjHUefhuK4H1OaSfIIFipFnuce6l3qw==,iv:2ardJfUcdnW0CnWActRp3Ii3M9eZUC89gdVsqu8qgOQ=,tag:ZaHsKZH7vXXsisU36hFsNg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY29uOW1oRFQ5bmJ3bHhv
        dGc1bDBYSFZMTDh0YVl6V2JpKzYwTVpJOTNzClhhSk1DTllMeE9VeC85RG5LZ1Ey
        ZWlueEdpdnhCSXJTMktacTc4aEdSczAKLS0tIERUb2hMdDY4b3JOVVlUMEpPb0pB
        RnpIcmVJVDh3cHNnVEJyVU0rODdiSFUKwX/GL4SzZzzQE+dFAge9y+MR/Zg8KVq9
        Gss+C8eCWgh4/0S6Q8PIslU1uEb6fyrQVEJ1uXpPLybtUaS+zF1Z6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTnpyWlM2MmlTYklHYjNG
        TGwwaVhiWFh5VWxsaThGL3Q2SFFDZDhVMkZFCnJSNGpIVDVGTGRGbzR4eXVHdlgv
        MU03SEdnRFpBZ0piZ2hiZ3F4WURPZk0KLS0tIHFTMU9QaHhJcXdNSFJTNXFVY3ZH
        NnVNenBycUdaQWxEZUxuc0JpZy9kVGMK1KVhmb0SK70nhFA3hxDcMPvs6tqR0aqv
        UnSMWkLUtCjvLgqIa9jS7FLsxl6ihJblebQ20Jt6UPHPu+c8emoWHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYW05dERUSEVxKzNUcEZ6
        d0NBV0F4L2E0Z00ya2pkZElxZFRvaDk4ZDJVCktZWTZpVlkrQy8yRmdnN2ErNERk
        L3hoVGZyMVZtRkxwK0FaKytvd0JuZU0KLS0tIHlhVTc4eTIya1JOeDlGVUwvZGFz
        QUtINlA1N0tCZFYwVklZRDdBYkFwYU0Kri6L6w6PuUHKTK1/uIO4FQBqUPSiOIkT
        lJKVnL57HnsmN2W/M8SkDgQjCY8hJ1Up9FccwRiW7jxT2NB/A5IQBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T00:59:33Z"
  mac: ENC[AES256_GCM,data:0FlQZbQujd95h27EXTF0hN7/0u1ZeRhVPXIqXCHp9BshPFImet4IDdKJFNY8+qZReE65/jxB+8GUYlCAVfx4OuQpFitYddJoq0Iww85fMANsZ8Dmq8uCu1Em1kEOu+xpfAdYTnmQXFhmh4MY0b6ogPuSTW6rXD8jvfgC3Cj9qeI=,iv:t66XQMGkJ5LTnWr3tpmym3nf6zKVNgSdT1+Azsdypis=,tag:3PfvGb41cMRtg2g3x+X/MA==,type:str]
  version: 3.13.1
