apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: productivity
stringData:
  ollama_api_base_url: ENC[AES256_GCM,data:fNFd1Ij6uMYzI9jJncQ0inB3bthBcjn2ZA5xmeYVDg==,iv:pUtzXUyNtQxiA3k1QOmVgbfrnoDrzkk+/Jv8v2zwXpU=,tag:f0LnQFqljq3E0e2zYQHeXg==,type:str]
  ollama_api_base_url_local: ENC[AES256_GCM,data:NEmWTmm6+FmgMYLEyXdT4bROS+HPRdwxy0C5/uKKkl2WD4EQiQ==,iv:w3940t6bZD6vf0XRVBHzwnrr0iZgS9srhG/q0p4+wRg=,tag:UAxTrmTqZmHNNmauuIxb7w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMHplclhvV2tnNkJla05Z
        NVJoc204Yjd3NUNLTW56U3NCNU5PZ1hMOEdvClptbWhCVld4RkxONWVVcjJjb0Zq
        TElGRXRQN1R2bUh1OVVmM2ZtQXZWcEUKLS0tIGZYL3F3NkpOTFRWdGRyczVZZEtS
        ZWR1a1VDQVAwVDl4dEg4NUVjamZ0b1kKEsXvguj9paft7dl2JcvhIr1kyivFwYj0
        Y73H7B3Qitxqqn7c9TIxnHVsFOpliwucQIQYs44X4wFmF6nswS3Xtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNVFPazBhNDFGTENQVmpL
        M3lWaUJrT3NuS054b2lkNFpEc0dWNnlwL1FFClpmNUNhODdXck1uVFV1TWV4dnFO
        TGx6RnZxeUNTTW9WSDU2UGQyTyt4WDgKLS0tIGw2WVJQTDRwY283RHNXbUdCZjVT
        QzZSdmZLcm1wQnlOZ0JzTTd6bDh1RWcKEvqHzqSwsiQGt3vIwbTEa7Y6m1mOShRV
        w+ek4BVRgQqgsTI+n9a93Y4aEidNaSthXnk7cPZTy4kHzYFOEIjCiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSTlWWlhadHc1UTRYZGtp
        S2s1NDNPWVQ4WThuSnNLd1U2aCtWdkFpTUdFClk5aUZGd1ZvNzJuTHdIWDJyMjhs
        OHhZZnhFVWx6NGVjVVJsRXl2bHVUOHMKLS0tIE04NEZTMzRwUVRvWEhCVE9aTzZZ
        WFVzcUxaR2owell0MjdDTGRKMTRkOFEKGBbmYqc3DsUVyFil8KuhuxtsKVlf868f
        vQBI/+qfjs9ESSVekFdyme/GRQJ1aomdWx+z3WM1z7qu9bZdk5njAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T08:49:29Z"
  mac: ENC[AES256_GCM,data:eoFBEu+QYAZnyb+KA9yGK9YcUnc2st3TJqvN2tYbchI/gedmfCk0oDdT2jG12dgogbibNOO4ShX1H2GQOUIOAjXTQXWivANmnU3HC13fGmjUNcypoCCkxFLil7FqlrSCz1tnVc4XpZPvHntqjcvI8RnsaCnGnM4VIQINlw2OhY4=,iv:oY2shuij0KNycswGbSbBNvswb+pfAAJkBXaZvuke6Vg=,tag:45tnTUWfw7mIcfhHl6Hlaw==,type:str]
  version: 3.13.1
