apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: productivity
stringData:
  ollama_api_base_url: ENC[AES256_GCM,data:adZr3Td51Qa5I4MiUK37H4+WtV63Y/jFN3t0b6Ce6w==,iv:E7W9nQdOyC2Q4xNtXDEi/8+A8os62jRKKcA87C+jXNc=,tag:FEXppi8Dm/mRqcwNdHBOig==,type:str]
  ollama_api_base_url_local: ENC[AES256_GCM,data:EnC/3VGGCoo3ltWQUhw0fqUdmBzmVl+Hbzkx9Hk4Au7YdoNJ2g==,iv:+fp2UwpDmR4hAiY9T3rSN7GoCnoklFWuSYcIw5CBZKY=,tag:QwQ1a9sAnbvyvAz3YF/rug==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYlhvVUx6aDVlOWJkWUEw
        UHI5UEhDSUVLY1NPNUo3SDE3OTRNakwrY0h3ClkrUHVMemUyQS92aUZkcFJSVDBt
        bVNzcXQybzRyUzlyRlBvMkw1ZENBUk0KLS0tIG5DWkpmYkFBYVQvSXpzdE95NTlP
        dG5ycGZsUS9xRDRBY2FoakRoSExpL3MKYYZfktEb3R91UIG/X1Aw80dfklj0FrbH
        n+Dc75YQLwCSNQ/u+diwqSBJQ9KHH7dSkmEwrqrvtHg0uP6OoQX6hw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRTFjV2hWc085WC9RUVNB
        b0NRSzRsZGF5U0F4WHVDQ0c1SnJYLy85VGpRCkUrWmJudnBTSHRBaVU1bFlkVWlJ
        NExSQmpPeldzT0IwZExOR2dSc0s1QVkKLS0tIE1KSjUyUFlmS2pXaVNONng3M1Vv
        bytEM0ZyL1QveCtlRlJpd255SCtTemsKLfJ9btegLN8fjXbUU5LK+HX2ui5w9TKU
        nElh1noSZir54Fuh1oK+jhxOtZF4j+uRktnx2fOkjY4DXMiodPu7Cg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1t067r55hvu848a4s92d2dn97xu8v8frcszh6403gsrqrkayp7f6sddhdgh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWWswUzcyWEgzT3QyZm90
        eTBXeUJwQzR5OThQWUtDaDRjVDZlV1k3WVF3CkZYbTdkUVBZaVB6ckN4ZFcyZXdz
        eWFvaDRSNERPWWwra0NzY2hHVXlMWmsKLS0tIFhFS3pHV1p3Tk1oYzdsVUVXSm9u
        cXhCbmRQb2huQ041MHZ6aFg2SWNTdkEKh82mrvxG1xCAx2YE5iOG7Rq1Nuhj5S+z
        cknmX6G3jzGdgVeHT4v7cZOE1OoCfX+2xJ31cuB8/5AFve4sle2niQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1w3jq4l9kaka6kx8pazvykv077dajde0qtgnsyeukgfcksu0w6epsltys44
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia0Rwb0FxczVXQWlJMWdG
        MXFYVmsxd1Y0dGRZd2JCZmpFZklYTmZXaWhRCjc3V3JxaWg2MUNZWmczRG10WXFH
        SzVubUJ4Q1J5SEVLOGFVRlYwMUxlN28KLS0tIG4yVW5pV0JoNFZIWGc0Yk51Vzd2
        RXZOVlc1d3l5dE1CWTgyemV1SmR6TVEK+sjfL8FvI6K8rr2CT3u0LDCo8sYF0QKv
        9976pZtRbfm/KtOmkOmD1phu8bn2JYVPQVU+LS3MIBT1ycViYhpApA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-27T02:39:34Z"
  mac: ENC[AES256_GCM,data:tRVWX1LGhOBkZbZFfDq/SyX7iC6hD6k9Itd1sIlCeDxx7aPqgZWZRWJuL/a3LQckvSjP+A3wz769SNI9qZ5hwrFhtBGxLHoSw/86nqZyW9+VkDE5+e3tePfyOWYOQ3bVEdRX/xi3OCL4IdRS/n4NCuLwE2x4jef9iFgdOxClfqQ=,iv:FL6XrNuGxLpqlqim0WEFMfstYpSxvRXyegKvGP9BTiQ=,tag:RYWoFeXBwDd+53VRX0mVNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
