apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: productivity
stringData:
  ollama_api_base_url: ENC[AES256_GCM,data:7t/ibaaZPcXD1TALR7Ij0E+N20WIV5eULpfcqEoPOg==,iv:prn70VnDwx9rSpla5PI4spuRTws6si0pRR96HpfZDsc=,tag:4C8IlFbdnkmFAMYgNLWcpg==,type:str]
  ollama_api_base_url_local: ENC[AES256_GCM,data:Rl91idD460eyfruf7+6IIJaqRgVkBGLm2+nJqV3C2IJaXyEkKQ==,iv:LUO7DlluYvz9xGBGzSin3LMo6pdiu6OvBl1JP2qwr1s=,tag:QQyN1mzw19fwiLbg9no5Tw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNlZOY3locmEwSXowbTBu
        V3krdzJrMncwSW9uQ3RJOTRjZ0hnTDU1eG1zCmlvSkhGbXNUQjNTM2FzVnhIcUw0
        eFpvbmpiejNXQTZUOU9WMllPNDdNZEEKLS0tIDBQY3dpM0hPZERXNm9zT0ZXYzBs
        VWRVckxUL1lYNm1RajBpd2k5RE53VU0Kf8jMp5LBOUZM0seEvrlzGikfDwN7x3+P
        gFtcUqT0F8fSFysbcMcVIUDqc3OxOrldXzWHm8gRdijJJEDot5NbAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU2Q4amxRTDVBSzhub1F6
        bXY4V2dMWEFiTUM3T0tmVzZnakovdmd1Qm5nCkNpNk5uUk8vb1lrcFFEa1ZmZm9n
        a3lyUTZ6UmVUNzkrbmtLclBQUHRjYTgKLS0tIFZYM1BudWcxSXhKS3E1a1p6a3la
        WmZXZjJWVjA0TkdKRURuSkFOcUVHYlEKjn1+XpLeUrwC14+7sXa/DglYNxE5QJRd
        Rno6vcA3i/m8Jg5xPCWhGo+MFw0xr4Tb4vWK9+C3ldDjAF1nlDh6+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMkJ6UTdCd214N1dCQmJM
        SnhwY202Rll0UGZEeEhUcUpnWWphQlpJVGdVCnpIMy90Qk5IQitsZ08vd3V4aDN6
        Q1NuMXNHWFRMREd0SUtSeUxjeUJhdjgKLS0tIGNaeFF5am5mOHJRcllNb3diaTlQ
        c2xnazRyMDhWRWd2cWxIUzBMbmhxVTAKoX8Gb2R8ZwGNPOw2H2fCQDDdDDwVL1Vh
        cZTIzB4aaAd1KVUtnOpR80+pxIVCrxaK/Ed2t9YbYy1pnJO4b+aA+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T09:27:20Z"
  mac: ENC[AES256_GCM,data:ZUeqHbRa8TF72Omclsa9hP1BxWiYHH/Kwq/3088IYJgRrMXlawbT4kSC1XFoH/fiC5CXJnsRdgrGymKY6hq/FqEfn76/Go7KCudTdT+TXlgUgUe70fXuBI3wC4adMLlZzMEtNCKEmiytWnWQwAIPyBt9OnMjITtAWIJJA1mb6K8=,iv:u0jPhG4UhaD0uZpRFE9bgJB4o1AfqKEQcI2+nImN96g=,tag:3rw74tr3aO/e8MqO7jgMIw==,type:str]
  version: 3.13.1
