apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName doplarr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *deploymentName
  template:
    metadata:
      labels:
        app: *deploymentName
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1001"
        - name: PGID
          value: "100"
        # The following environment variables are required for the doplarr container to run
        # This is set in the overlay for the production environment
        # - name: DISCORD__TOKEN
        # - name: SONARR__URL
        # - name: RADARR__URL
        # - name: SONARR__API
        # - name: RADARR__API
        image: lscr.io/linuxserver/doplarr:latest
        imagePullPolicy: Always
        name: doplarr
      hostname: doplarr
