apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: calibre-web-deployment
  template:
    metadata:
      labels:
        app: calibre-web-deployment
    spec:
      containers:
        - name: calibre-web
          image: linuxserver/calibre-web:latest@sha256:802729966faed5e32d671cd4f92ba6196e9e754a6c0f740ce1ee9acd86b10e55
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1001"
            - name: PGID
              value: "100"
            - name: UMASK
              value: "007"
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: calibre-web/config
            - name: media-volume
              mountPath: /books
              subPath: calibre-web/library
      volumes:
        - name: config-volume
          nfs:
            server: ${NFS_STORAGE_HOST_FAST}
            path: ${NFS_STORAGE_CONFIG_DATA_PATH}
        - name: media-volume
          nfs:
            server: ${NFS_STORAGE_HOST_FAST}
            path: /mnt/mopower/swarm-data
