apiVersion: v1
kind: Service
metadata:
  name: calibre-web-service
spec:
  selector:
    app: calibre-web-deployment
  ports:
    - name: http
      port: 8083
      targetPort: http
      protocol: TCP
