apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf-service
spec:
  selector:
    app: audiobookshelf-deployment
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30378
  type: NodePort
