apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: productivity
stringData:
  jwt_secret: ENC[AES256_GCM,data:wN52OZnHdKJ6MQ+o1Sisnepd8dWJPmc=,iv:vKjxFibpLQnxRJr8PvrmBqwsNu7/nHO4BJY7Ine0JBA=,tag:c0vpBhMikBopA/OvxXoFwg==,type:str]
  session_secret: ENC[AES256_GCM,data:aigJXVuXN6Lpi49sXfRZfporSRAg1xHduDW0/ToTsHJVH89QMD8dSLm3CAlBhLzolKQCxx53L547hRZF+8oJbkcna5YW34GscgajbRkf6o0hM7swhODcZ2lPmCJ+PbOdeAgSULPFyCpF5CHx2C9H9IuerQwOqJsfbCWrN7Xc0sNL,iv:6N3K3uVbWSK6wg+NCT8Np239aj6giXnjX1VtP5HMGb0=,tag:583Oa4CUE7c5GDV64IUASg==,type:str]
  storage_encryption_key: ENC[AES256_GCM,data:Sxx84lCThbLv+HYU1W5eo3Oq7BdE,iv:Ax5pEE9wfiKcKMceDeYSOMMW56nkY+X+8p/vgSMx+V8=,tag:qe+cjdcaSPwUqVpA5fKViA==,type:str]
  smtp_password: ENC[AES256_GCM,data:9cyYy/8aTZ4D6IwTQBq7xg==,iv:A3XNBuUywKiG+iMRknZ+DJ9vcX0hFIvSlsw35QZgubM=,tag:/151YYl49tf2I3IzeGCXTA==,type:str]
  duo_secret_key: ENC[AES256_GCM,data:OiHkmI2Z+6xvxxGDrClYxG836/8VSGL7afa4nvbVaY0GSD+XJg4G8A==,iv:e3e0XCQB6fah2d9D7Kmu17/WEJvwdFTkIgumU8BYy2M=,tag:/CL38Im7EgGEfJ8KpkPVQg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETXI4TEd6QThXQW5LLzlq
        eEdpdGt0R2JRT01PTXlHb0dQZjJzU0JGb2xvCjBjR052cFBnVGlQbDFnLzFITUlp
        WW11S0xNMkRTcTNnUzc5OUV5RW15dXcKLS0tIHhBM1pHWDduQjdZbUxsVW1GUkJV
        MmYzb3M1UlhPS0RGaFZEaENMNDMwVkkKz5D8dJ2HGU9f4Q6zn5IwLVafpNis06x2
        on6RCGyXu8ojiGTSi8FodSfyfDOC8ZQJ4PbK2kPcNHrEsy16GraB4g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVXdldkJqclBKQ0xHZDE0
        a3lNT1ZKZEZ6Um80bWN6eXBGU1UrVTlQVVhvCkJRa3poUjlNSzBlQkZUaTJjLy9Y
        SE12RGFjaXBqbWQ1STRBNDdhZUl6UWMKLS0tIENVZ2greDBYZE5BVmNBT1Z3c2gx
        dWtVMXJveWFDNmkvNFMvSk9KNnUzQ2cKvdMDwj8TMkQrOvHDkxImkIMsfANaGsQA
        c7GUBj4m9Y5AImefA1KRbKy/wRE9BDO9w7AO5GfB2PR/iqsmc2ozZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnejhjNTZxamZqN3p0V3U3
        dHlvSlViUnA0ZkZIeUpLb3pyZERrTmg4S1VnCkpNSnZtMXFqYWFPbFROOFpTNk5u
        OXhuajNZVDJEL3ZhMEhab01tK1B5MU0KLS0tIFlYbUNlSmIxRmFEajdYVm12MStu
        MjVsaXc5RmpwS2hjNVpoVnhTcUl5UTgKZPz5bvdeSphIaRalAxsDsyQOu8TLAXmw
        yeT7BxuBMU9JOyQrT+ACpmuHN+t9tsmVnOvLCNINbb3qzckLs6WYLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T22:03:31Z"
  mac: ENC[AES256_GCM,data:7E1yTblS7beSocl+rfumgc/N+MlKdZatkhhYatk+xFzvGfaW8jQYqrgH/3CnUQ3Gqq2OO4O/hBFAdBXxmeet96B6DeBL8xDMCijKVJ2U9ynf5o4vU1G5qVWrA7rMKIxa6lu4HcTtMBsYJiAkUcUYOIjC4KdBDNEOEO9Li0fHUVM=,iv:vBJ/i/nuHQ9BtrMUAlvggIwoCE40hbTcwdF+ZL0IK40=,tag:WkxyEuJAduxRVUycG/Q9Bw==,type:str]
  version: 3.13.1
