apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName open-webui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *deploymentName
  template:
    metadata:
      labels:
        app: *deploymentName
    spec:
      containers:
        - image: ghcr.io/open-webui/open-webui:main
          imagePullPolicy: Always
          name: open-webui
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /app/backend/data
              name: config-data
              subPath: open-webui/config
      hostname: open-webui
      volumes:
        - name: config-data
          nfs:
            server: ${NFS_STORAGE_IP}
            path: ${NFS_STORAGE_CONFIG_DATA_PATH}
