apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: media-service
spec:
  selector:
    app: jellyfin-deployment
  ports:
  - name: http
    port: 8096
    targetPort: 8096
    protocol: TCP
    nodePort: 30096
  - name: https
    port: 8920
    targetPort: 8920
    protocol: TCP
    nodePort: 30920
  type: NodePort
