apiVersion: v1
kind: Secret
metadata:
  name: hermes-agent-secrets
  namespace: productivity
type: Opaque
stringData:
  HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:Ni1LAgo=,iv:Y5IJhFA3FW6jClecGoohhyUzY5JkN9EZsvzmED7vT8Y=,tag:V4ZAoMesPuVKnwxBjGPJ/w==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:L+WAK+EqSykq/ppeikAUq3/JO1A=,iv:Zjljb9p7Rm3TMZb1lm0M7P2KL7ya8oQu8LoafMzYjmI=,tag:qoqJ7qcV2yntZzulcqnvAQ==,type:str]
  API_SERVER_KEY: ENC[AES256_GCM,data:tYMEXC2HLw8XEmYoHpnZkV+Y8Le6YSEfjsPMnE0bOsdfl6KmIM6O6l8vSZTyrlmtCZvDitWcB2Lni+ABCVkMPQ==,iv:aFuBve1OYS3pCD8jO5DBEHl8ex/YUOJAPuPDYPN/D5Y=,tag:whPRulrUBqfeoPrGqRuD1A==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:ky9cpAndtXlqrnksW/NUW1hDI1wJ0oJGR4UoiEykWG419O9yBxS9XLeiAgMxgVgnUm1Pkz0ZNkgQnPb/RPI3KuBlshYhJ4S508fsbZE91Fs4W0g8tFnLxiZnAjTGyT+fmS46x1QZ87IqTQycZo6q8iozSFhs2sOa8s+wXscsk+CJ/fzsLSeG+zZ+D9Ow+i9x47hF+mo75W87FY6XFcZIyJ4aCtQ=,iv:3OzZ9A860zhSR3l8coutHAqX4WRU/+dGgGeMgFXF4GA=,tag:QgO/n7YCdkNI6QoYGgw+DQ==,type:str]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:LWhP2Vi2BxNjGUys2P5acyhSIxAkztmqK+aeH+EBV6ZclTBdbDFUpLkcAZGvoR8ysrMgppqbmMMAUMPhcveJYTfrqe3Lp2mj,iv:C6+lUuOJymVB27+3FRSKu/xm1f24qtQVo852Yjgt7C4=,tag:ZpogGKeWXXtndkcSSMgQXQ==,type:str]
  DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:d3wNDcEbg0G9YhxIR0YIxgnm,iv:3Nf85U6tZ4e/do1YTfFWQ6p0WfuAvG8FcR84LgNdnAI=,tag:cfwEdF14W3Rl47B1vKe3ow==,type:str]
  DISCORD_REQUIRE_MENTION: ENC[AES256_GCM,data:Z6sqDg==,iv:Y4yhJJrgdkr4MtRQCanUe6UAbmAD9x9NUDYf3n2ToNA=,tag:zGT+anUzRbARglwXknHn8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYjRaZlpTZGJzcjFaM25a
        Tjk2dnBDTEtreE9RNXQ0WDh3Rnk4TTNZSlRnCkVZa1RhQ0MxbGlEK1VJUVJENkxY
        MmNMVmwvUnROcnJMYjN1OENzNllvdGsKLS0tIDdRL2g0L1VCeUVRaWFOSE8vTEk4
        aEFWQXNTRTVsSEV1L2d0TUhhMzNMVlUK8g6sCyc8/U3MVQaj5SFiOMoOwzep9wJ7
        b+FQw48scp/+cVwozC90sjkeSJIWah4rvHJouIFPHrLi1snLx6EtKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TWl0TSt2L1RQRlFRakFW
        STlwR1EzRWE3SUhabzFvcnhXLzlXWUVYU1ZzCmFzbDAwYW5xQ2ZQdlBYaStybDFt
        N3p1WC9QU0dIa1NvNHRMdjJuQURoZU0KLS0tIDNIcFBGNGRQbkQ4MHZWYWdxWHpz
        YzJBdGhSb0FwOUYvREZ4UFBtZWZjWVUKB2j1h9PmfRkSkW/T1+pqECzQafpAbmma
        ZEl1XxsQ4nYsf9YbZSPKKjS/z/16CQ0waExvGf09ZJf4vyjgyzjZBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNVZxL2hoaFRxeGNITjh1
        T3ZCdEdjU2ErWC9Cbis3QmlkbGhkL2VTYVJzCjk4cDJFM2JIblY4cjFzY0h6KytZ
        Tzg5NFlxdVZCUm5VWUdKc2M2Qmg1NmsKLS0tIHVZeER2ekZ6SmJvUHVEcU1BcEFs
        c0ptbk1MbjVZQ1ZiVEloUng5ZHNmRE0KhscGiurXfpENhn9vqeI8HCm6deZdfdT0
        +9phIfqc5fz9fnzajWbRNhjitPXM/yI6pF0XwlgXRYHvUWGuei/Olw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T00:21:11Z"
  mac: ENC[AES256_GCM,data:j3JfqLS5+D6mfrouZ1D4NJfsCdgQuMD1b5oH3OLw/RDQHlwJ2NuCR3765coOPLOGN22ICa+yIOY1qZ33XG9KDSAYV9bOk31uTH//2I7dIfqMfcFxr7ycNaoywVzRQ7IVbQayssCfFCDU5XlJ+7JVn/dS1wCP/hSC85IOlyWesUQ=,iv:65FN7Jt40x2zz3vjj/v/hQyuLEzVKNQ1qD5qxu0EmaU=,tag:CcPIcx8Vo1e/ed+KQ67jZw==,type:str]
  version: 3.13.1
