apiVersion: v1
kind: Secret
metadata:
  name: hermes-agent-secrets
  namespace: productivity
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:Ayyvhfm3c7tXoGwdch2AZPuh+JgneACjVGfsUFNv,iv:qgpxALyuFaWUcDXLWSIlrMQaueeL3qat6ckZ7Ei6fFM=,tag:bxivYZKO8F/tYsH0jrO6SQ==,type:str]
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:xzWIKwo1NahGyWamtC69hXZ6/FsTNSyXXrbvxCx/,iv:cqpbPTKlCnOJR13VmtMuYihGxKOCF4S9phREm/UfK8Q=,tag:KqOMZoQsQOUc3KO4DOl+rg==,type:str]
  TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:oxuuG+nSoGfud4c7iU11kIadC/QaXodJSJZuWXD2UUbYFQ==,iv:A10PP91x/jnysCr9L7Bob5M9jAWR1qMeyIt3UzS4oCU=,tag:0WMSbe1N2wLp5eQ+CT04Hw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdWpZOHBIbmNxZXJHTVlo
        RHlqN3hWdGpPdXFuRjJWK3pJbHpKN2hYekRBCk13NUYrZmJaZmFkaXJ6QldUV2VR
        VERzVTZmRWVkNjhuTzB4SEM1U0FXeGsKLS0tIFlJUWs4ZUZ4QkpTN21GcFR2enhV
        cXFIaVpRR2VjN1NENlJJeEY2bXpDWlkK+AYLwZg/ockFu5qrkuVRfGWFuoEf1lLp
        6bY76fhEWeIwE+tbY3ntJ+jOyzHfYNM7tgUyydyLTuFVfvzJ2m+zLQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOVUyWHlaU3hPTmYrUE9s
        M3ZpSGlyNWo2aGNMWHY0MnNwbUVMeTdKNEVNCkZYcnNuOU1TTG1NOVFQZEh5VGt0
        MGI1cEVQbWNMb2REYytseS80NGQ5bFkKLS0tIDBKOXBTOC9IS0xGN3JnakV0dTN2
        VjlXVWp1T0gxTXpoMWVkY2JXZ0hQMm8KwTuHXtFPGZfqdXlpKr5zL/X8CJPZLXZm
        2I1biqd2ES3k8GO0nbngQ5vNl7yyUtwbc3FnJwb8JVL5XV3guvkplw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZDNaN1lobG5STk9VL2Zx
        aGU3SGl4Tlc3aXRPRjE4aDk3NUNUblVkMHhBCmlJTFhGTWtBenJSbGFJUHVMVVMz
        RDJrTDhUdUltUHRaek43TWs4eFZONUkKLS0tIFROeU1nckNKcGxUaG1odU52VEVL
        ZFV4ZWppQkUwRDIwaG5jdExFZnVsZGMK46gRvcAcd/YhyoQeTORPaL7XavEMz1HD
        dDeroapU0OW6duVwNq7k1kjcVIN9kxBzjy64e5osgFllsNc55L9e4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T14:35:02Z"
  mac: ENC[AES256_GCM,data:Vee1CQEVL69yn9ZR4ehzDvT+mhN3tXtAHOWLKze+Joars1jyaFbSC8r7+SjK6i/JJ1WBzG4G/D3VmMmzjguWcA1/3+gDZNc7HC8XqkiKI09eMbAEodaYOFZdeC4J65ajulwgWso2j2vI3tUDx0h1zpqtZfq7DMS5NYaVAE6NJm0=,iv:vVBJ6FbxWUGHrhqqPrS75HlWZqVu2Ni0NvQNKiJ2brg=,tag:9FD3vMg+t0QkgmgQdDeFUg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
