apiVersion: v1
kind: Secret
metadata:
  name: hermes-agent-secrets
  namespace: productivity
type: Opaque
stringData:
  HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:Ni1LAgo=,iv:Y5IJhFA3FW6jClecGoohhyUzY5JkN9EZsvzmED7vT8Y=,tag:V4ZAoMesPuVKnwxBjGPJ/w==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:L+WAK+EqSykq/ppeikAUq3/JO1A=,iv:Zjljb9p7Rm3TMZb1lm0M7P2KL7ya8oQu8LoafMzYjmI=,tag:qoqJ7qcV2yntZzulcqnvAQ==,type:str]
  API_SERVER_KEY: ENC[AES256_GCM,data:tYMEXC2HLw8XEmYoHpnZkV+Y8Le6YSEfjsPMnE0bOsdfl6KmIM6O6l8vSZTyrlmtCZvDitWcB2Lni+ABCVkMPQ==,iv:aFuBve1OYS3pCD8jO5DBEHl8ex/YUOJAPuPDYPN/D5Y=,tag:whPRulrUBqfeoPrGqRuD1A==,type:str]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:LWhP2Vi2BxNjGUys2P5acyhSIxAkztmqK+aeH+EBV6ZclTBdbDFUpLkcAZGvoR8ysrMgppqbmMMAUMPhcveJYTfrqe3Lp2mj,iv:C6+lUuOJymVB27+3FRSKu/xm1f24qtQVo852Yjgt7C4=,tag:ZpogGKeWXXtndkcSSMgQXQ==,type:str]
  DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:d3wNDcEbg0G9YhxIR0YIxgnm,iv:3Nf85U6tZ4e/do1YTfFWQ6p0WfuAvG8FcR84LgNdnAI=,tag:cfwEdF14W3Rl47B1vKe3ow==,type:str]
  DISCORD_REQUIRE_MENTION: ENC[AES256_GCM,data:Z6sqDg==,iv:Y4yhJJrgdkr4MtRQCanUe6UAbmAD9x9NUDYf3n2ToNA=,tag:zGT+anUzRbARglwXknHn8Q==,type:str]
  GITHUB_APP_ID: ENC[AES256_GCM,data:Zks6xsz2GQ==,iv:lX2KBVzXETe5UcbX9N6KtYtrTPSE2M1IpQxMN9QijPg=,tag:7/9mRwwFl6on8Rn6ZkNOrw==,type:str]
  GITHUB_APP_INSTALLATION_ID: ENC[AES256_GCM,data:+iFSv910/Lfe,iv:IRMK825ACqGXXv0Ca/LYH7TAYMeGAAE15W4pIT6g8io=,tag:dNTWHSNgQLBgAz0AKIimIg==,type:str]
  GITHUB_APP_PRIVATE_KEY: ENC[AES256_GCM,data:78LZG3xi/JoQCdlyt6C0pyp7Wy/50bK/W4XPcOrmQgkEFn76anv+/n76XVpqzz1iZdJtBuNnILheAg7DoycmXGb1g8dDuAEbpNxfHsSXeQg4ncH261C2bwX8hfb4Bb9HahX8g0XWUNVsb5fKouSikDjyTV3KJvI+ws+c2Gcr+8s0H7HuK5ZThaJ43vblEUDvP8ijzUYDALJZt0ngUyDYOH8FH7tlWKuLnubymODsh95KKAys9iZjaDsEpz5MkB5tAOCW3eaQRK6r7E1ajYE7mtLQwpWdSX49ZV3Ihzl/YtDVDPqKcrHL3A0V9QHFNwUhg2X9twcqG2OufwsilZR+ZFJlewboss5X7dXSxp9q4AZPWKPZTQ+PXvRz1199D7x3LLlnVvtuYfuE1H49WafaWREDn38eDbj1bW2SonAfnr1ydsZK21w8uj4Rytgcg2l+d5NaOZri64I9O9pxAwlXk/kVZJzGA19RlUxcHxfVjBusW9FwuGkP+txevlzTezJ4Rl8FaicPuEVdrvb1zf5gUTTv0oKjKcW110oytFWuTf6ooljZIOss2Np49IbQyDOF/hkP3IUR7pAycQK5DP86CnVrfuEJNH0vAC+sRi9jrPgQ5db+Hsv4WZUkIj2j85iGmwRnbai8e55uKC0rY0vQkRzuO1RrKoedopDMakru86alLZZuC2mw8KVglsO9Cxvs9oxTmhRxSGIA7Q9wGuXQqbrbShxGOfDx/SCdfmMyIlLvwhw+D520JnZWKyOAdd51R1Fpd6xljnBT6EoTDBMDu7by/Jje1T+oH+Ob2LVOsUAnkpRaGI8T6gs7asLWSnw3xF4UiC7KYOMULH/evReBd/kpYkksQI7CEdruW/07G3pH6rkz/KSnSxGOZkaI/5Vk8jSmB7Cd/6pdy0fMhDRBhgif9JX5zH22k3CiL4kEhTARNuNw9qOoGK8mQsuWPOK2R7+GSJ0R56kkQwXq1kbjVm9JGt9raUakE2xs4U21w1ZN5T25JZSi/Mj8E+X5Pz+KPNq6bYB3FRxbpBQ3HEy1Wc+p9YPVFNDSGAtKz/m04WqiPeoE2k6t8KJAe/CQzB23+ysedeM0ywWKxa3ut/4GaKiedYdkhSYkgKLvkDIv+hBUexznaZJJfskWKAqe6H5Jaj5oAFgYPHDOy2NiDIvlJeolxGze+LCfI6eV56L3Z3V+D3ITvNL6UbmdZ+fooSFgNrvopkYRXPQJyCF0N7U3wLFGyNmPpu9stkVhto5nZeagO7kPZLNk2iE66Zp0Ac3n6D1yhJ9Z4rVcLDiZkVLmtwuU9bXA8Vi7733etLiILFI+FCVHOoPiAY7uRTLT+SFokRVnX6g/lMpoargrwVo0oyI7nLyzWxCf/ZEEh7qE5KTjWHY8bFZMhzTtG1gs2BPlXRaotxocuYlQ43vev3gr6JXbWA2r/K2RFNRlpda2RjlYO6+mTW3+frfpbsrL/xBEl2bhtH62FmqUfi/uCRnwriD2gUJkifVYWBOqzxTmzPx+YfQLJSXkB5ogm+PXUHWsRbo+9kY1cfPdxHOx6rAvMjyKx+0Pazr0e9RPQEa5Q4g+51spTQaSTQhVINdiW+7cswMVXphISEUQAK8GEWgIBv/RzitV9zct3sOVLWaTs3ssYkgt0hzs+jvdGJI5n6HiRyNheo1uPlGxJb+26Htw/aOV69xCzMEeNwiwxHBwY88uG0fstxnEZ4zVug3X5exZtYlxWwFSJ9AqubB0xIodzNiI9ojnI1X+kdVNbVuVIyB9Vh42uEQYOlHfwBlFUmfqIiXssQKJTxnp5xtmYUklAybl0gtVIYkndUIVXZ4WI0pA0+FLi6v9ZatsD6MT/9RhnuTcfuUce+Yb0xAnhf0pATb/ciycO8ZuVbhMzC4rA3Uh5oIh2viMl6gkL1Gl9bzX0eqRt+QOSCOYCudfop02x2WVJWmHTOEnbz3UFidYg3X6HgWn00pS3K/hjSsaAX2Wj6Za4rNbRTrJ1AYCoaIleEvMO0T6ZvIPSuGizG9i95coGEBq0PVFlzl61/e3DPklO44jVtyjq05WQbh1YuU/21HP7fr3aXkFOTIJxlsTLq1slRYD/PtrIoujnKVJrAhLDzcss6iUW9VsVwiQ1coqcKRsrjdrhLThh8Q9eK4l2BQrSTj/hHNN+pBJW9Io7Lz0Eb1SwfM8Z27dlg4DBqem2GopiVZB26nV5MNGNGuAwCrAZ2Lgy1Suc8rs9In05Ok=,iv:qNR+AfeXnD+aftpscaODnbtbRoDvOEmItomTpg2vlNA=,tag:SQeu6ZpxofLWlGINtBXLtg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYjRaZlpTZGJzcjFaM25a
        Tjk2dnBDTEtreE9RNXQ0WDh3Rnk4TTNZSlRnCkVZa1RhQ0MxbGlEK1VJUVJENkxY
        MmNMVmwvUnROcnJMYjN1OENzNllvdGsKLS0tIDdRL2g0L1VCeUVRaWFOSE8vTEk4
        aEFWQXNTRTVsSEV1L2d0TUhhMzNMVlUK8g6sCyc8/U3MVQaj5SFiOMoOwzep9wJ7
        b+FQw48scp/+cVwozC90sjkeSJIWah4rvHJouIFPHrLi1snLx6EtKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TWl0TSt2L1RQRlFRakFW
        STlwR1EzRWE3SUhabzFvcnhXLzlXWUVYU1ZzCmFzbDAwYW5xQ2ZQdlBYaStybDFt
        N3p1WC9QU0dIa1NvNHRMdjJuQURoZU0KLS0tIDNIcFBGNGRQbkQ4MHZWYWdxWHpz
        YzJBdGhSb0FwOUYvREZ4UFBtZWZjWVUKB2j1h9PmfRkSkW/T1+pqECzQafpAbmma
        ZEl1XxsQ4nYsf9YbZSPKKjS/z/16CQ0waExvGf09ZJf4vyjgyzjZBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNVZxL2hoaFRxeGNITjh1
        T3ZCdEdjU2ErWC9Cbis3QmlkbGhkL2VTYVJzCjk4cDJFM2JIblY4cjFzY0h6KytZ
        Tzg5NFlxdVZCUm5VWUdKc2M2Qmg1NmsKLS0tIHVZeER2ekZ6SmJvUHVEcU1BcEFs
        c0ptbk1MbjVZQ1ZiVEloUng5ZHNmRE0KhscGiurXfpENhn9vqeI8HCm6deZdfdT0
        +9phIfqc5fz9fnzajWbRNhjitPXM/yI6pF0XwlgXRYHvUWGuei/Olw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T22:12:17Z"
  mac: ENC[AES256_GCM,data:KHqaxaBrJ1ki1RRlSu8ifR0yD/84LBcSGOFHzP5P2+d3LkTHL5Sukr6tUMf6nX8fT+zJYHxaDLYAuVQ3PoZlBeJxGU7aU67VfFUesnEoPALSZIIkn9HdVwxjAPcSA5nBcgH1xnmmCTFc2c+cKb2c6WuKGKdAHhx4+hpAOywPViA=,iv:jZIH+b5UBYzhp7kc8kuCPn705AvIe10dP/bcrb15BDQ=,tag:d8c01iXAj4u5J9rbgvHxbA==,type:str]
  version: 3.13.1
