apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./github-app.sops.yaml
  - ../../../base/kube-system/actions-runner-controller

patches:
  - path: ./patch_helm-release-runner-set.yaml
    target:
      kind: HelmRelease
      name: arc-runner-set
