apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord-alert-provider
  namespace: flux-system
spec:
  type: discord
  channel: kubernetes
  secretRef:
    # Use the secret from cluster-secrets
    name: discord-alert-provider-secret
