apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-webui-deployment
spec:
  template:
    spec:
      containers:
        - name: hermes-webui
          env:
            - name: HERMES_WEBUI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hermes-agent-secrets
                  key: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD
            - name: HERMES_WEBUI_GATEWAY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hermes-agent-secrets
                  key: API_SERVER_KEY
