apiVersion: v1
kind: Secret
metadata:
  name: csi-driver-nfs-secrets
stringData:
  server: ENC[AES256_GCM,data:AyYx7Lf5XAfMK7Fychgckta1QbRO6mQKKU9oJB2InesN8eOZVg==,iv:V1LMwW7P+FYoE5H3YhKo7ztFV19Yro+NQPpr6sXXJ1g=,tag:g1WIJb64gi/DvYG+QM+NzA==,type:str]
sops:
  age:
    - recipient: age1kak7nac7pp9kel9cl43m93jdrdtzdqhw07dkc62hk0qvq37u05nqce5mf5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVFRPQkluSkJyR042T1RI
        SGZ2aWVSTkNoa2doeGZvQkJXRFczWm1jMmtrCitwb1VaYzM4Mi9PT1VmUW0wYVpy
        aHNyN0lMSFB5YXVCN3F6a2VtVUgvbTAKLS0tIHpMMy9zV2hUMjB4aVJlUS9jUExp
        aVkzdHNEbVpPTzJZSDlxajk5ZXF2aGsKBDLqzAi9pfiB6bljyAmTIX7mQGvrutcr
        LjIEiIEP0IN7hAD7PrFK3QlzHOK5gD2Mtz/o/cHNTWl5pfdNBsEyog==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sx0dh82apfxxdv9z0l77dmu00e9vz5rn3pfwwnxhwumdxmwy7gsshaxxlc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcXFkT1VMWXMxUlZPa3g3
        VElCcThsamMybVdvbXZFNGo5SkNUV0lILzM0CkJtUDBBeEpsSjI2bXFoTVZ0b1F4
        dlBXbEdLYnJkMjZveGJTQWVYVVhPdjQKLS0tIFZaRDFHQnRkY0lHS1lxT0lGUU9n
        eGQ3L3hlTnJxNVhUWlA1VTVOcStTbW8KtuReJIYxrTgq1EWpUd8kt1WZbKJFgQyq
        ADTkQSXLSGEny6ofh/TeQtMn9oYdzNEJ6qQR6x14cdNV31/3RAMMsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ffeq7wngvj64rk8xv0syfrfqxpstst5wlld2dxqwr52wr3z9hv5qhyuwsd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWWtzaE1Ca3JVODlvV0da
        cVJ1WnlQczdsTEMwbno4MU1wdDdXZE5oNkI0ClBtSmdyZE9hTGQ1TStWUUtCTDRu
        L2lYanVNY0ozVHpTV09aUVZNY09lTlEKLS0tIEpLaFpQRzkrdWp5Wk8yc2M3NTRV
        TzdHVzNpR1NBVkV4ckJiOS9IdG9sL2MKQ8vTj/p478UwbQqMRL3RDatxYZN1WWDs
        xZtyffs8T4MkfuSvyPzUx6WM7Nkrb4FBBMtBETzOJu/ZdBpHD0TaVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T01:17:52Z"
  mac: ENC[AES256_GCM,data:3LuxwnwNgZNeeeJhI6Mna34tv4r3qdocmwEfKXSe5rtUI37t5QCZYuTPXBf6m90CSbfx0LRadfpmJwME/bC4AESGWOYLMarfJ8hMCWhPM7G6bBe81n3j4WUFVLMZQIPsTQBG39Pn2bWenC9MarzvWcvQRvTFRUN+1+f3rcswGm4=,iv:i3/oTxQbL7YC16KFIpRBmjBZHfct1tJe3mYvBYfUWM4=,tag:4Mq9aYUz8esN8S+wI1+aHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
