apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName ombi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *deploymentName
  template:
    metadata:
      labels:
        app: *deploymentName
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1001"
            - name: PGID
              value: "100"
          image: lscr.io/linuxserver/ombi:latest@sha256:aa44c36e0c79a8c53dcf6c7f03559c8fcead701cece03a2ee1d08a3e6f13b4d5
          imagePullPolicy: IfNotPresent
          name: ombi
          ports:
            - containerPort: 3579
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config-volume
              subPath: ombi/config
      hostname: ombi
      volumes:
        - name: config-volume
          nfs:
            server: ${NFS_STORAGE_HOST_FAST}
            path: ${NFS_STORAGE_CONFIG_DATA_PATH}
